### ISSUE TITLE
Time picker

### ISSUE THREAD

**Issue by wakirin** [wakirin/Litepicker#1]

**Comment by kl3sk** [comment]
I was looking for a no dependency time-picker and found yours very interesting !
Time option will be a great enhancement.

Any news about it ?

**Comment by wakirin** [comment]
Not yet, doesn't have enough time to do this.
I plan to do this as a module so that this will be optional, since as will affect the file size.

**Comment by kl3sk** [comment]
Yes it is a good option, for me at least. Eager to see it in place

**Comment by kl3sk** [comment]
Hello, @wakirin do you found time to do it ?

**Comment by wakirin** [comment]
Hello @kl3sk,
Unfortunately no, I'm busy on other projects.

**Comment by kl3sk** [comment]
Ho, bad news. Your picker is no useful, adding time will be so great.

Thank you for this work again. 


I may help but don’t no how.

**Comment by liborm85** [comment]
It would be great to see support of time in Litepicker, ideally by scrolling as in following figures:

![image](https://user-images.githubusercontent.com/1298652/83353975-84474680-a356-11ea-8548-a29c77f6273f.png) [screen from xdsoft timepicker](https://xdsoft.net/jqplugins/timepicker/)

![image](https://user-images.githubusercontent.com/1298652/83353989-a345d880-a356-11ea-9290-fa0c9000ce4a.png) [screen from mobiscroll](https://demo.mobiscroll.com/jquery/datetime/time-picker)

**Comment by cah-briangantzler** [comment]
While time picker as a stand alone would be great its really a separate component. I would like to see time picking integrated with the date and date range options. http://www.daterangepicker.com/#usage does a nice job of picking the time within the date

**Comment by kl3sk** [comment]
@cah-briangantzler the daterangepicker solution to pick time is not very convenient I think.

Select are not UI/UX friendly.

**Comment by cah-briangantzler** [comment]
I was referring more to the positioning within the calendar (as opposed to separate inputs) than them specifically being selects.  

What is considered UI/UX friendly with respect to the time inputs. (In case I get time to try a PR, and not take a route that is going to be rejected)

**Comment by kl3sk** [comment]
No worry, I just said that the default select break the design IMO.

Please add a PR 😄

**Comment by cah-briangantzler** [comment]
Can you point me to some guidelines so what I create has a better chance of being approved?

(As you, I dont have the time right now, but hoping to get some eventually)

**Comment by kl3sk** [comment]
I'm not a maintainer but I can point you at @wakirin [module range](https://github.com/wakirin/litepicker-module-ranges) you can look at this to make a compatible module.

**Comment by strarsis** [comment]
Though I would like to see a Timepicker with Litepicker in a more decoupled manner, like using this extra component https://github.com/grudus/Timepicker.
For a full time picker integration, the days would have to be splittable into hours or even finer blocks where the time can be selected (if intended). Otherwise it would be just two timepickers, each for start/end datetime value next to the calendar.

**Comment by liborm85** [comment]
@wakirin Hi. Is there a plan to implement this feature?

**Comment by wakirin** [comment]
@liborm85 

I'm thinking of doing it as a plugin with [input[type="time"]](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time).
And a fallback for unsupported browsers, as @cah-briangantzler suggests above.
When ? Sorry, I don’t know yet when I will have the time and desire to do this.

**Comment by wakirin** [comment]
Use [easepick](https://easepick.com/) with [time-plugin](https://easepick.com/packages/time-plugin)
