### ISSUE TITLE
autoRefresh option doesn't work with custom date format

### ISSUE THREAD

**Issue by roipoussiere** [wakirin/Litepicker#101]
**LitePicker version**

v1.4.5

**Describe the bug**

The `autoRefresh` option doesn't work with custom date format.

**To Reproduce**

When using this simple html:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <script type="application/javascript" src="/static/js/vendor/lite-picker-with-css.min.js"></script>
</head>
<body>
<input id="date-range"/>
<script>
var date_picker = new Litepicker({
  element: document.getElementById('date-range'),
  singleMode: false,
  inlineMode: true
});
</script>
</body>
```

The date is updated in the date picker.

But when I specify a custom date format:

```html
<script>
var date_picker = new Litepicker({
  element: document.getElementById('date-range'),
  singleMode: false,
  inlineMode: true,
  format: 'DD/MM/YYYY'
});
</script>
```

Then the date is not updated in the date picker.

**Expected behavior**

The date in the date picker should be updated, whatever the specified date format.

**Comment by wakirin** [comment]
I think this issue related to #98 
Try with v1.4.7
