### ISSUE TITLE
numberOfColumns is 2 in inlineMode with mobileFriendly and portrait orientation.

### ISSUE THREAD

**Issue by McRip** [wakirin/Litepicker#102]
**Describe the bug**
The numberOfColumns stays 2 when using inlineMode together with mobileFriendly and when beeing viewed in portrait mode.

**To Reproduce**
Create an inline Litepicker and display it on a mobile. Instead of one Column the calendar is rendered with two columns wich breaks mobile layouts.

**Expected behavior**
On a mobile device render only one column when using an inline calender in portrait orientation.

**Comment by wakirin** [comment]
fixed in v1.5.0

**Comment by McRip** [comment]
Thank you very much!
