### ISSUE TITLE
Plz add Tags to releases

### ISSUE THREAD

**Issue by VanSnitza** [wakirin/Litepicker#106]
I'd like to encourage you adding tags to your releases. 
For example  v1.5.0 to your latest commit.
This would make it easier for me to have your nice module cleared for use in a professional project.

**Comment by wakirin** [comment]
There are no releases https://github.com/wakirin/Litepicker/releases

What do you mean ?

**Comment by kl3sk** [comment]
I think he means taging every version released.
The latest v1.5.0 may have a git tag as `v1.5.0` or `1.5.0`

**Comment by wakirin** [comment]
So, a suggestion to add a tag for each commit?
Like that: `v1.5.0, update readme` ?

**Comment by kl3sk** [comment]
No, juste on new releases version (I suppose).

As you will may push to npm only on new version I suppose.

**Comment by VanSnitza** [comment]
Thanks kl3sk for clarificartion. It's exactly what I mean. 
I need to have every OSS Component cleared by a special department in my company. Whenever I pass a reference to them, it was easier using a tag than rather than the commit hash.

So, for example whenever u push to npm, just add a tag on this repo too. Then the reference would be (for example) v1.5.0 == 406b117070a0ef0c53d42a280fe3aa0de8922079

**Comment by wakirin** [comment]
Well, as you can see in the screenshot above I am already doing it.

**Comment by VanSnitza** [comment]
Thank you very much :-)

**Comment by kl3sk** [comment]
# At least on NPM
![image](https://user-images.githubusercontent.com/2953145/84787705-9bd92d00-afee-11ea-829f-c61ec9eef11b.png)

# But not on Git
![image](https://user-images.githubusercontent.com/2953145/84787677-91b72e80-afee-11ea-9c66-a3a1f240589b.png)

But I don't know on which platform @VanSnitza talk about

**Comment by scott-fisher-iii** [comment]
Right. I think it would be nice if the releases section in GitHub had the tags.
For those of us that use the CDN link (https://cdn.jsdelivr.net/npm/litepicker/dist/js/main.js or a versioned link) it would nice to be able to see the tracking in GitHub.

**Comment by wakirin** [comment]
Ok, I will start adding tags on Github in future releases.
