### ISSUE TITLE
undefined is not an object (evaluating 'screen.orientation.angle') on Safari

### ISSUE THREAD

**Issue by tjura** [wakirin/Litepicker#107]
Safari not support screen.orientation.angle
https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation

[Error] TypeError: undefined is not an object (evaluating 'screen.orientation.angle')

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/3449794/84827112-43bd1d80-b024-11ea-8b06-7e7a5b4f59ed.png">

**Comment by wakirin** [comment]
Should be fixed in v1.5.1
Thanks.

**Comment by tjura** [comment]
Nice job! I am impressed :)

śr., 17 cze 2020 o 08:27 Rinat G. <notifications@github.com> napisał(a):
