### ISSUE TITLE
The dates are off (showing 6 per week)

### ISSUE THREAD

**Issue by manmar** [wakirin/Litepicker#11]
The dates are of in my case (version 1.0.17):
<img width="338" alt="Screen Shot 2019-12-17 at 2 02 35 PM" src="https://user-images.githubusercontent.com/353314/70998046-a285f680-20d6-11ea-9c7b-4d55d192061e.png">

Solved it temporarily by adding:
```  
div._1GaIWDB6QXdrLKd3z7NcAQ {
  box-sizing: content-box;
} 
/* center the days */
._3RNHHNUGhQ-NpbLrnVDa8s {
  text-align: center;
}
```

P.S. 
Tx for the plugin :)

**Comment by wakirin** [comment]
I don't see at the moment this problem on demo page.
I would be to know do you use any css framework ?

and about class names like this `_1GaIWDB6QXdrLKd3z7NcAQ`, from v1.0.18 class names are readable (discuss here #6).

**Comment by manmar** [comment]
It's a custom framework, but it's 
```
* {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
``` 
from the CSS reset that breaks it.

**Comment by wakirin** [comment]
Thanks, I've added `box-sizing: content-box;` to `container__months`.
