### ISSUE TITLE
Calculate how much days/nights are chosen, when we have two separate inputs with Litepicker

### ISSUE THREAD

**Issue by VaninaDzhuteva** [wakirin/Litepicker#110]
Hi again, I have new case: we have a two separate input for arrival and departure dates initialized with Litepicker. On date select we want to show on some block under the inputs how much days/nights are chosen. The problem comes when I want to get the chosen date on change event of the corresponding input (it is not triggered, I saw that it already you closed another issue about it). So how could I get the selected dates outside initialisation of Litepicker without using change event, so I can calculate the difference between the two separate dates?

Thank you!

**Comment by wakirin** [comment]
You can count how many days in the `onSelect` event.
Outside Litepicker you can use the `getStartDate` and `getEndDate` methods and calculate how many days.

**Comment by VaninaDzhuteva** [comment]
Ok, but how to catch the change when I use onSelect?
 `if(arrivalInput) {
	var arrivalPicker = new Litepicker({ 
		element: arrivalInput,
		numberOfMonths: 1,
		numberOfColumns: 1,
		inlineMode: false,
		singleMode: true,
		mobileFriendly: true,
        showTooltip: true,
		onSelect: function(val) {
            parent.classList.add('form__group--filled');
			arrivalDay = moment(val).format('DD/MM/YYYY');   			 
			return arrivalDay;  
		}
	});
}`
When I use it like this I cant get the new value that is chosen, because OnSelect is getting the current date. Here I have only the arrival date, I have another initialisation for departure. Click event is not catching the change eather.. So what are my options?

Thank you!

**Comment by wakirin** [comment]
from docs:
> Example: onSelect: function(date1, date2) { console.log(date1, date2); }

So if you need to get the end date, you must use two parameters in the event.

**Comment by VaninaDzhuteva** [comment]
I have one input element for arrival and second input for departure. When I use onSelect, the second element is undefined, because I am not using it like one input for range picker. They are to separate initialisations.

**Comment by wakirin** [comment]
I think that instead of two initializations you need to use only one with `elementEnd` option.
In this case you will receive the start and end dates in the `onSelect` event.

**Comment by VaninaDzhuteva** [comment]
Well, I have a design that needs to be completed. In this case that you are describing how to manage to show the calendar on the second input field? 
![Capture9](https://user-images.githubusercontent.com/17564311/85299023-71cfb100-b4ad-11ea-962d-b4f87379cc3e.PNG)

**Comment by wakirin** [comment]
Have you checked `elementEnd` option ?

**Comment by VaninaDzhuteva** [comment]
I am not sure how I can use it, can you give me example please? Thank you!

**Comment by wakirin** [comment]
https://jsfiddle.net/waki/9kztrsqp/

**Comment by VaninaDzhuteva** [comment]
Hello, there were some changes in the requirements for the calendar. If the arrival date is chosen first automaticly to add 7 days for departure, and if the user chose first departure date - nothing to happend. I managed to use both of arrival and departure values with separate inputs and not using elementEnd. So here is the code:

var currentDate = moment().format('YYYY/MM/DD');
var arrivalInput = document.getElementById('arrival');
var departureInput = document.getElementById('departure');
var departureDayFormat = '';
var arrivalDateFull = '';
var departureDateFull = '';
var departureDay = 0;
var arrivalDay = 0;
var arriving = '';
var departure = '';
var countNights = 0;

if(arrivalInput) {
	var arrivalPicker = new Litepicker({ 
		element: arrivalInput,
		format: 'DD/MM/YYYY',
		minDate: currentDate,
		numberOfMonths: 1,
		numberOfColumns: 1,
		inlineMode: false,
		singleMode: true,
		mobileFriendly: true,
               showTooltip: true,
		onSelect: function(val) {			
			// Get arrival date in DD-MM-YYYY format
			arrivalDay = moment(val).format('DD/MM/YYYY');  
			
			if(departurePicker.options.startDate === null) {
				// Create date for departure, adding 7 days from arrival
				departureDayFormat = moment(arrivalDay, "DD/MM/YYYY").add(7, 'days');
				// Set the appropriate date format for departure date
				departureDay = moment(departureDayFormat).format('DD/MM/YYYY');

				// Set the value of the departure input
				departurePicker.options.element.value = departureDay;

				// Add style for form__label
				departureParent.classList.add('form__group--filled');
				// Count how many nights are chosen 
				arriving = moment(arrivalDay, 'DD/MM/YYYY'); 
				departure = moment(departureDay, 'DD/MM/YYYY');
				countNights = departure.diff(arriving, 'days')

				if(departure > 0) {
					document.querySelector('.number-nights').innerText = countNights;
				}
				else if(departure <= 0) {
					document.querySelector('.number-nights').innerText = "0";
				}
			}
			else if (departurePicker.options.startDate !== null) {
				// set full dates to be compared
				arrivalDateFull = val;
				departureDateFull = departurePicker.options.startDate.dateInstance;

				// Set the appropriate date format for departure date
				departureDay = moment(departureDateFull).format('DD/MM/YYYY');

				arriving = moment(arrivalDay, 'DD/MM/YYYY'); 
				departure = moment(departureDay, 'DD/MM/YYYY');
				countNights = departure.diff(arriving, 'days');

				if((departureDateFull <= arrivalDateFull) && (countNights !== NaN)) {
					document.querySelector('.number-nights').innerText = "0";
				}

				else if ((departureDateFull > arrivalDateFull) && (countNights !== NaN)) {
					document.querySelector('.number-nights').innerText = countNights;
				}
				else {
					document.querySelector('.number-nights').innerText = "0";
				}
			}
		}
	});
}

if(departureInput) {

	var departurePicker = new Litepicker({ 
		element: departureInput,
		format: 'DD/MM/YYYY',
		minDate: currentDate,
		numberOfMonths: 1,
		numberOfColumns: 1,
		inlineMode: false,
		singleMode: true,
		mobileFriendly: true,
		showTooltip: true,
		onSelect: function(val) {		
			if(arrivalPicker.options.startDate !== null) {
				arrivalDay = moment(arrivalPicker.options.startDate.dateInstance).format('DD/MM/YYYY');
				departureDay = moment(val).format('DD/MM/YYYY');
	
				// set full dates to be compared
				arrivalDateFull = arrivalPicker.options.startDate.dateInstance;
				departureDateFull = val;
	
				arriving = moment(arrivalDay, 'DD/MM/YYYY'); 
				departure = moment(departureDay, 'DD/MM/YYYY');
				countNights = departure.diff(arriving, 'days');
	
				if((departureDateFull <= arrivalDateFull) && (countNights !== NaN)) {
					document.querySelector('.number-nights').innerText = "0";
				}
	
				else if ((departureDateFull > arrivalDateFull) && (countNights !== NaN)) {
					document.querySelector('.number-nights').innerText = countNights;
				}
				else {
					document.querySelector('.number-nights').innerText = "0";
				}
			}
		}
	});
}
