### ISSUE TITLE
Internet Explorer is broken after #93

### ISSUE THREAD

**Issue by scott-fisher-iii** [wakirin/Litepicker#111]
**Describe the bug**
It looks like the implementation for [#93] broke the usability in Internet Explorer 11.
The browser console yields this error:
<pre>Object doesn't support property or method 'from'</pre>
It is referencing this section of code:
<pre>if ("asc" === this.options.dropdowns.years) { 
   var v = Array.from(f.childNodes).reverse();
   ...
}</pre>

**Setup**
HTML:
<pre><script src="https://cdn.jsdelivr.net/npm/ie11-custom-properties@latest/ie11CustomProperties.js"></script>
<input id="picker" type="text" />
</pre>
JS:
<pre>var pick = new Litepicker({
	element: document.getElementById("picker"),
	dropdowns: {
  	   months: true,
  	   years: 'asc'
	}
});</pre>

**Comment by scott-fisher-iii** [comment]
For some reason my input element is not showing in the HTML setup, but it is just:
`<input id="picker" type="text" />`

I tried to make a JSFiddle, but it no longer supports IE11.
https://jsfiddle.net/fnpyc6gs/2/

**Comment by wakirin** [comment]
fixed in 1.5.7

**Comment by scott-fisher-iii** [comment]
My QA team confirmed this is no longer an issue after upgrading to v1.5.7. Thanks!
