### ISSUE TITLE
Wrong months in dropdowns before 1995 in iOS

### ISSUE THREAD

**Issue by golfbal** [wakirin/Litepicker#113]
When using the dropdowns options "years : true" and "months : true" i noticed that before 1995 there are issues with the months. 
This only seems to happen on mobile iOS devices, i haven't been able to test on desktop Safari as i have no such device.
I have tested this on nl-BE & en-UK locales, it happens on both locales.

For example : 
- 1987 (and a few other years) has no October, and two September's: 
![image](https://user-images.githubusercontent.com/43927963/85718189-8fd82400-b6ee-11ea-88ea-0816b56887e3.png)

- 1950 has March twice, and no October: 
![image](https://user-images.githubusercontent.com/43927963/85718340-b5fdc400-b6ee-11ea-9dee-bc81a40baab7.png)

Additional info :

Litepicker V1.5.4
Litepicker config : 
```
var picker = new Litepicker({
                element: this.$refs.dateField,
                lang: app.locale,
                format: this.question.format || "DD/MM/YYYY",
                dropdowns: {
                    minYear: this.question.answers.min || 1900,
                    maxYear: this.question.answers.max || null,
                    months: true,
                    years: true,
                },
                mobileFriendly: true,
                onSelect: function (date) { self.setDate(date); }

            });
```

**Comment by wakirin** [comment]
fixed in 2.0.1
