### ISSUE TITLE
input format changed by litepicker

### ISSUE THREAD

**Issue by Quenos** [wakirin/Litepicker#114]
**Describe the bug**
My inputs are rounded boxes
As soon as the ID of the input is attached to element in JS, the input becomes square on the right side

**To Reproduce**
HTML:
```
<form>
    <div class="form-group">
        <div class="input-group" style="width: 150px">
            <div class="input-group-prepend">
                <span class="input-group-text" style="font-size: 14px;">Till</span>
           </div>
           <input class="form-control" type="text" id="date_start" style="font-size: 14px"></div>
    </div>
</form>

```
JS:
```
const { ipcRenderer } = window.require('electron')
const { Lightpicker } = require('litepicker')

var picker = new Litepicker({ element: document.getElementById('date_start'),
                              elementEnd: document.getElementById('date_end'),
                              singleMode: false,
                              onSelect: function (date1, date2) {ipcRenderer.send('dates', date1, date2)}
                            });
```
<img width="443" alt="Screenshot 2020-06-28 at 20 59 17" src="https://user-images.githubusercontent.com/34926461/85955923-53bcf180-b982-11ea-8cc9-d1a38f2a70c4.png">

**Expected behavior**
See the rounded input box on the left:

<img width="455" alt="Screenshot 2020-06-28 at 21 01 18" src="https://user-images.githubusercontent.com/34926461/85955970-8b2b9e00-b982-11ea-9d2d-1b91fbe613b3.png">

**Additional context**
Used in desktop app under electron

**Comment by wakirin** [comment]
I'm not sure if this is Litepicker's problem.
I tested here: https://jsfiddle.net/q1b0hr5g/
Input doesn't lose `border-radius`.
