### ISSUE TITLE
possibility to select several unconnected days

### ISSUE THREAD

**Issue by heleon19** [wakirin/Litepicker#115]
We have an application where we want to select several unconnected days. 

There should be a single mode with the possibility to select several days. For example I want to select the 25 June 2020, the 30 June 2020 and the 5 July 2020 on the datepicker.

![image](https://user-images.githubusercontent.com/10326318/86088764-3b92c280-baa7-11ea-8566-a83bc18e7fd4.png)

**Comment by heleon19** [comment]
Any news on that topic?

**Comment by wakirin** [comment]
@heleon19, @ninetyninew, @ghost, @etwordpress01

Anyone still interested in a multiple choice datepicker.
I have prepared the first version of the multiselect plugin.
Currently in beta 2.0.2-beta.0

Demo: https://jsfiddle.net/zq8gbhe7/

Below is the plugin documentation:

# Multiselect plugin

Adds multiple selection.

Litepicker version 2.0.2 or higher is required.

### Installation

```html
<script src="https://cdn.jsdelivr.net/npm/litepicker@2.0.2-beta.0/dist/litepicker.js"></script>
// include plugin after Litepicker
<script src="https://cdn.jsdelivr.net/npm/litepicker@2.0.2-beta.0/dist/plugins/multiselect.js"></script>
```

If you’re using a bundler, e.g. webpack, you’ll need to import Litepicker first.
```bash
npm install litepicker@2.0.2-beta.0
```

```ts
import Litepicker from 'litepicker';
import 'litepicker/dist/js/plugins/multiselect';
```

Now you can create Litepicker instance with plugin:

```html
<script>
const picker = new Litepicker({ 
  element: document.getElementById('litepicker'),
  plugins: ['multiselect']
});
</script>
```

# Options

### max

Type: `Number`

Default: `null`

Optional. Limits the maximum number of days selected.

Example: 

```js
new Litepicker({
  element: document.getElementById('datepicker'),
  plugins: ['multiselect']
  multiselect: {
    max: 5,
  },
})
```

# Events

### multiselect.select

Arguments: `(date)`

`date` is DateTime object. 

Event is called after select day.

```js
...
setup: (picker) => {
  picker.on('multiselect.select', (date) => {
    // some action
  });
},
...
```

### multiselect.deselect

Arguments: `(date)`

`date` is DateTime object. 

Event is called after deselect day.

```js
...
setup: (picker) => {
  picker.on('multiselect.deselect', (date) => {
    // some action
  });
},
...
```

# Methods

### clearMultipleDates

Arguments: `()`

Return: `void`

Clear selections.


## getMultipleDates

Arguments: `()`

Return: `DateTime[]`

Return selected days as DateTime Objects.

## multipleDatesToString


Arguments: `(format, delimiter)`

Return: `String`

`format` is optional, default is `YYYY-MM-DD`. Allowed formats see in `format` option of Litepicker.
`delimiter` is optinal, default is `,`.

Return selected days as string.

**Comment by wakirin** [comment]
Plugin added in v2.0.2

https://wakirin.github.io/Litepicker/docs/plugins/multiselect/
