### ISSUE TITLE
Get extent of view

### ISSUE THREAD

**Issue by strarsis** [wakirin/Litepicker#117]
@wakirin:
**Is your feature request related to a problem? Please describe.**
Sometimes it is necessary to know what view the calendar shows as a whole (range from start to end).

**Describe the solution you'd like**
A function that returns the extent of the current calendar view, 
a range/period or list of ranges (for split-view) the calendar currently shows.

**Describe alternatives you've considered**
Currently, I have to calculate it myself (using the number of months option).
This is much harder with split-view calendars.

**Comment by wakirin** [comment]
`onRender` event should help here.

```
onRender: function(element) { 
    console.log('picker element', element); 
}
```

`element` is main container of Litepicker.

**Comment by strarsis** [comment]
@wakirin: But I would still have to query for all the day DOM elements and then use the first and last one for finding out the actual range?

**Comment by wakirin** [comment]
Maybe I don't understand very well, but if you use something like that:
```
onRender: function(element) { 
    [...element.querySelectorAll('.is-start-date, .is-in-range, .is-end-date')].forEach(el => {
        // here some action for each day in the range
    });
}
```
I do not plan to include this specific action in the package.

Could you show your current solution and result ?

Thanks.

**Comment by strarsis** [comment]
```js
// get the extent of calendar view
function getCalendarViewExtent( pickerUiElem ) {
    let dayElems     = pickerUiElem.querySelectorAll('.day-item');
                                    // Note: if the calendar adds days of previous/next month to the month days, modify this line to filter these out!
    let firstDayElem = dayElems[ 0 ];
    let lastDayElem  = dayElems[ dayElems.length - 1 ];

    let firstDayDate = new Date( Number( firstDayElem.dataset.time ) );
    let lastDayDate  = new Date( Number(  lastDayElem.dataset.time ) );

    return { // [date-fns interval]
        'start' : firstDayDate,
        'end'   : lastDayDate,
    };
}
````

**Comment by wakirin** [comment]
I am assuming you have `autoApply: false` in your configuration and you want do some action on preselect dates ?
If so, in v2 will be added two events: `onSelectStart(startDate)` and `onSelectEnd(startDate, endDate)`.

**Comment by strarsis** [comment]
@wakirin: Ah, in this case I want to know the displayed range of the calendar so only that corresponding data can be requested from the server. For example, when the range 01/01/2021 to 01/01/2022 is displayed, the data for that range should be requested from the server and then applied. Currently I have to check the calendar DOM to find out the actual displayed range, including overlapping days (from previous months) that are also shown in the calendar (usually greyed out).
