### ISSUE TITLE
Displayed vs value delimiter

### ISSUE THREAD

**Issue by strarsis** [wakirin/Litepicker#122]
**Is your feature request related to a problem? Please describe.**
Currently, the delimiter option is used for both, displaying and setting the value.

**Describe the solution you'd like**
Having a separate delimiter option for the delimiter used for displaying the date range.

**Describe alternatives you've considered**
Using a handler for setting the value, with a different delimiter.

**Additional context**
https://github.com/wakirin/Litepicker/issues/94

@wakirin: This is really an issue because the user sees a delimiter (like `,`) that is needed internally as field value.

This is very related to the date format itself: The user should see a different date format than the actual value of the input field.

**Comment by wakirin** [comment]
1. Add `onSelect` event.
2. Add `<input type="hidden" />
3. Set the desired format as you need in the hidden field in `onSelect` event.

**Comment by gaelgerard** [comment]
Bonjour,

I guess @wakirin answer should resolve my problem but I'm not sure how to manage it in my code.

I got a simple form in which I want user to get the date in french format but I need to set the value in american format for my database.

The fields:

```
<input id="day_from_picker_indisp" class="form-control required" name="day_from_indisp" data-prop="day_from_indisp" type="text" placeholder="Sélectionner une plage*" required  readonly="readonly"  />
<input id="day_to_picker_indisp" class="form-control required" type="text" name="day_to_indisp" data-prop="day_to_indisp" required readonly="readonly"  />
```

The Litepicker script:

> var dt = new Date();
			 dt.setDate(dt.getDate()-1);
			new Litepicker({
				element: document.getElementById('day_from_picker_indisp'),
				elementEnd: document.getElementById('day_to_picker_indisp'),
				singleMode: false,
				lang:'fr-FR',
				format:'DD MMM YY',
				resetButton: true,
				allowRepick: true,
				minDate: dt,
				tooltipText: {
					one: 'jour',
					other: 'jours'
				},
				tooltipNumber: (totalDays) => {
					return totalDays - 1;
				}
			})

Now I can easily add hidden input fields to my form, but how can I populate them with the yyyy-mm-dd format?

Thank you for your help and the great plugin!
