### ISSUE TITLE
 iOS, v11, v12

### ISSUE THREAD

**Issue by forwardever** [wakirin/Litepicker#124]
**Describe the bug**
on iOS, v11 / 12 (Browserstack)) Safari: the start date can be selected with one click, end date can be selected with one click, but calender window does not close (like in iOS v13), a third click is required to close the window -> this is confusing, as third click can go on another end date, resulting in an unexpected date range

**To Reproduce**
tested on Browserstack Safari iOS v11, v12, several devices (iphone and ipad)

**Expected behavior**
window closes with selection of the end date

**jsfiddle.net / codepen.io / etc**

**Additional context**
singleMode -> false
autoApply -> true
showTooltip -> true

**Comment by forwardever** [comment]
to solve this issue for now, i have deactivated the showTooltip option

possible problem: Double-Tap issue
https://css-tricks.com/annoying-mobile-double-tap-link-issue/

**Comment by wakirin** [comment]
fixed in 2.0.1
