### ISSUE TITLE
preventDefault for next month button with nocss not working

### ISSUE THREAD

**Issue by heleon19** [wakirin/Litepicker#125]
Hello
Thank you for the great date picker.

preventDefault() ist with nocss not working. The url changes to #. In my case the page reloads.

I use import Litepicker from "litepicker/dist/js/main.nocss";
Klick on next or previous month arrow
The page is reloaded, due to url change with # 

When I use import Litepicker from "litepicker";
It works as it should

**Comment by wakirin** [comment]
Try to add these styles:
```
.litepicker .container__months .month-item-header .button-previous-month>svg, 
.litepicker .container__months .month-item-header .button-previous-month>img, 
.litepicker .container__months .month-item-header .button-next-month>svg, 
.litepicker .container__months .month-item-header .button-next-month>img {
    fill: var(--litepickerMonthButton);
    pointer-events: none;
}
```
