### ISSUE TITLE
onCancel

### ISSUE THREAD

**Issue by strarsis** [wakirin/Litepicker#129]
**Is your feature request related to a problem? Please describe.**
The Litepicker range selection can be cancelled by clicking outside the picker and inside the document,
and the previous selection is restored (range or none).
No event is fired when this happens, no selection or error event.

**Describe the solution you'd like**
A cancel event (`onCancel`).

**Describe alternatives you've considered**
It may be possible to find out about cancelled selections by using the picker DOM itself, 
which is very cumbersome and brittle.

**Additional context**
This is similar to https://github.com/wakirin/Litepicker/issues/116.

**Comment by wakirin** [comment]
with v2 you can do something like this:
```js
 // ...
  setup: (picker) => {
    let isCancelled = false;

    picker.on('preselect', (d1, d2) => {
    	isCancelled = !d2;
    });

    picker.on('show', (el) => {
    	isCancelled = false;
    });

    picker.on('hide', () => {
    	if (isCancelled) {
      	// some action
      }
    })
  }
// ...
```
