### ISSUE TITLE
Detach CSS from main.js

### ISSUE THREAD

**Issue by AlexCSR** [wakirin/Litepicker#13]
**Is your feature request related to a problem? Please describe.**
I want to write my own CSS code instead of redeclaring hardcoded styles.

**Describe the solution you'd like**
Use JS and CSS separately, not both in one bundle.

**Describe alternatives you've considered**
Loop over all document.styleSheets and disable Litepicker's one  ¯\_(ツ)_/¯

**Comment by kevinmu17** [comment]
This is so wrong haha, hell no to !important almost every style element.

**Comment by wakirin** [comment]
Well, you can import your style without `!important` in the body section.
I don't planning detach css, I like it more to import just one file.

**Comment by kevinmu17** [comment]
What a shame... It would greatly appreciated if you did so the community can build themes. bloating 2 complete stylesheet is a pure waste of bandwith and feels wrong. Why not splitting things up in litepicker.core.scss and litepicker.theme.scss and leave the freedom how to load to the dev community?

**Comment by wakirin** [comment]
Your way is looks the same, you still need to import two files (core and theme).
Shame ? Well, you are free to create fork and support any features what are you want.

**Comment by AlexCSR** [comment]
Okay so while you're doing open source software for your own needs only, here's a snippet for folks who want to do that I wanted to:

```
    <script>
      // Remove LitePicker default styles
      [].forEach.call(document.styleSheets, function (css) {
        if (css.href || css.ownerNode.innerText.search('litepicker') === -1) return;
        css.disabled = true;
      });
    </script>
```

Use it after all your scripts.
