### ISSUE TITLE
Dropdown should match the max date when opened

### ISSUE THREAD

**Issue by bennybobw** [wakirin/Litepicker#133]
**Describe the bug**

```
      this.form = document.getElementById('form-weather-data-area');
      this.startDateElement = document.getElementById('start-date');
      var maxDate = new Date(this.startDateElement.dataset.yearMax);
      var today = new Date();
      if (maxDate > today) {
        maxDate = today;
      }
      this.litepicker = new Litepicker({
        element: document.getElementById('start-date'),
        elementEnd: document.getElementById('end-date'),
        singleMode: false,
        maxDays: 180,
        useResetBtn: true,
        dropdowns: {
          minYear: this.startDateElement.dataset.yearMin,
          maxYear: this.startDateElement.dataset.yearMax,
          months: true,
          years: true
        },
        maxDate: maxDate,
        minDate: new Date(this.startDateElement.dataset.yearMin, 0, 0),
      });
```

In this case when the maximum date it set to Dec 31 2019, when I open the picker, the dropdown shows 'September 2019' when the calendar is actually displaying 'September 2020'. I'd expect it to load the month with the last selectable date, not the current date, since that's not pickable.

**To Reproduce**
Make a calendar with min date set to anything and max date set to Dec 31st 2019

**Expected behavior**
Calendar will open to December 2019. Instead calendar opens to Sept 2020 and dropdown shows Sept 2019.

**Comment by wakirin** [comment]
Fixed in v2.

**Comment by PlippiePlop** [comment]
Hi, this fix causes a problem. 
If you set a minDate and Maxdate for example previous month and next month. it will jump to the next month. while you expect it to go to the current (today) date /month. 

[Example fidle.](https://jsfiddle.net/USRFobiwan/gervkqdw/)

**Comment by wakirin** [comment]
@PlippiePlop 
Ok, I will fix it in next release.
Thanks for the example on jsfiddle.

**Comment by PlippiePlop** [comment]
A workaround is to set it to current date on rendering:
`if (picker.options.inlineMode) {
      picker.render();
        picker.gotoDate(today); // temp fix to set it to current month/date
    }`
