### ISSUE TITLE
Feat: support weekday in "format" setting

### ISSUE THREAD

**Issue by er314** [wakirin/Litepicker#136]
Can you consider adding support to render the weekday, for the output format ?

Via 2 new keywords, e.g. "dddd" & "ddd" , or "EEEE" & "EEE", depending on the chosen convention,
which would call date.toLocaleString() with parameter weekday:'long' & weekday:'short' , respectively.

This would allow to render some (pretty common & UX-friendly) output in the likes of :
**Tuesday** September 29
**Tue** September 29

**Comment by paullryan** [comment]
@wakirin Both this and #152 would benefit from the ability to override format and parseDateTime with a passed in function as an option then a custom function or a library like luxon can be used to do this operation as this library currently lacks support for a large number of date time formats 

Examples of formats that mostly don't work yet (these are internationally recognized formats for a number of countries):

```
[
    { format: "yyyy-MM-dd", expected: "2019-11-23" },
    { format: "dd/MM/yyyy", expected: "23/11/2019" },
    { format: "d/MM/yyyy", expected: "23/11/2019" },
    { format: "dd.MM.yyyy", expected: "23.11.2019" },
    { format: "yyyy-M-d", expected: "2019-11-23" },
    { format: "d.M.yyyy", expected: "23.11.2019" },
    { format: "dd-MM-yyyy", expected: "23-11-2019" },
    { format: "MM/dd/yyyy", expected: "11/23/2019" },
    { format: "d.MM.yyyy", expected: "23.11.2019" },
    { format: "d/M/yyyy", expected: "23/11/2019" },
    { format: "yyyy年M月d日", expected: "2019年11月23日" },
    { format: "MM-dd-yyyy", expected: "11-23-2019" },
    { format: "dd.MM.yyyy.", expected: "23.11.2019." },
    { format: "yyyy.MM.dd.", expected: "2019.11.23." },
    { format: "३/६/१२", expected: "३/६/१२" },
    { format: "yyyy/MM/dd", expected: "2019/11/23" },
    { format: "H24.MM.dd", expected: "024.11.23" },
    { format: "yyyy. M. d", expected: "2019. 11. 23" },
    { format: "yyyy.M.d", expected: "2019.11.23" },
    { format: "yyyy.d.M", expected: "2019.23.11" },
    { format: "d.M.yyyy.", expected: "23.11.2019." },
    { format: "d-M-yyyy", expected: "23-11-2019" },
    { format: "M/d/yyyy", expected: "11/23/2019" },
    { format: "d/M/2555", expected: "23/11/2555" },
    { format: "๓/๖/๒๕๕๕", expected: "๓/๖/๒๕๕๕" },
    { format: "yyyy/M/d", expected: "2019/11/23" },
];
```

It's even more complicated for localized date parsing of formats like 'MMM dd YYYY' where any language can used for MMM and you'd need to parse the lang set first then tokenize (the AST get's pretty nasty).  I've currently got my own fork where I use luxon for this job and it works great (I did an inline replacement for the internals of your datetime library, however like I said it really is just those two functions that need to be able to use a third-party in some situations).

**Comment by wakirin** [comment]
I will add the feature to use an external library for parse and format output in v2.
The v2 release is late January.

You can already see changes here #157 
I will update the post about the option` format` change soon.

**Comment by wakirin** [comment]
Use `format` with external library.
See example: https://wakirin.github.io/Litepicker/docs/options#format
