### ISSUE TITLE
when hotelMode, setting minDays=1 should prevent selection of same start/end

### ISSUE THREAD

**Issue by er314** [wakirin/Litepicker#137]
I think that when in hotel mode (where minDays actually means "minimum nights"), 
and especially when explicitly setting minDays=1, 
the user should **not** be allowed to select end date = start date (instead, he should be allowed to select end date = start date + 1).
Currently it's allowed, so it is "visually awkward" to have a hotel booking from 2020-10-03 to 2020-10-03.

Moreover, this current behavior for minDays=1 is a singularity, compared to minDays=2 and above.

Server-side (upon submit) this situation can easily be circumvented, but anyway client-side it's visually not well.

do you agree ?

**Comment by wakirin** [comment]
The option `hotelMode` was removed in v2.

Use:
https://wakirin.github.io/Litepicker/docs/options#lockdays
https://wakirin.github.io/Litepicker/docs/options#lockdaysfilter-200
