### ISSUE TITLE
Month/Year dropdowns not behaving as expected in Firefox browser

### ISSUE THREAD

**Issue by jcardonadcdev** [wakirin/Litepicker#138]
**Describe the bug**
Month and Year cannot be selected from dropdowns in Firefox after a start and end date have been set. The list of Months/Years disappears as soon as the mouse is moved into the options list. This happens when `allowRepick` is `true`.

Litepicker constructor used:

```
var picker=new Litepicker({
    element: document.getElementById("datepickerstart"),
    elementEnd: document.getElementById("datepickerend"),
    singleMode: false,
    allowRepick: true,
    dropdowns: {
      months: true,
      years: true
    }
});
```

**To Reproduce**
1. Go to https://codepen.io/jcgisman/pen/vYGozVK using **Firefox**
2. Click on the `Start Date` input
3. Click on a day to select a start date
4. Click on a day to set an end date
5. Click on the `Start Date` input again
6. Click the `Months` dropdown in the date picker header
7. Move your mouse into the options for Months
8. See that the options disappear as soon as the mouse enters `January`

**Expected behavior**
I would expect that the options to choose a Month would remain visible and that I could select a new Month for setting the start of the date range

**jsfiddle.net / codepen.io / etc**
https://codepen.io/jcgisman/pen/vYGozVK

**Additional context**
* Firefox version: 82.0b6 (64-bit) on Windows

**Comment by wakirin** [comment]
I don't see Litepicker on the url you provided.
