### ISSUE TITLE
Setting picker.setOptions on click of a future day reverts the calendar back to the current month

### ISSUE THREAD

**Issue by adamboother** [wakirin/Litepicker#141]
I am looking to set the minDays option on click of a day, due to a different minimum stay applying depending on the day selected within the calendar. There doesn't seem to be a 'setMinDays' method so I am doing this on click of an active day and grabbing the date via the data-time attribute. I have my calendar set with the following options:

```
let picker = new Litepicker({
                element: document.getElementById('availability-calendar'),
                inlineMode: true,
                singleMode: false,
                format: 'DD/MM/YYYY',
                numberOfMonths: 2,
                numberOfColumns: 2,
                hotelMode: true,
                selectForward: true,
                minDays: 3,
                lang: 'en-GB',
                minDate: new Date()
});
```

On click of a day I'm then setting this via:

```
picker.setOptions({
                minDays: 7
});
```

This is working fine but when I click my first day, e.g. 1st September 2021, the calendar then flicks back to the current month (October 2020) rather than staying on September 2021. Does anyone know why this may be?

**Comment by wakirin** [comment]
with v2 and [preselect](https://wakirin.github.io/Litepicker/docs/events#preselect) event, you can do something like this:
```js
// for example you need to change minDays when user selected Sunday
new Litepicker({
  element: document.getElementById('datepicker'),
  singleMode: false,
  setup: (picker) => {
    picker.on('preselect', (d1, d2) => {
       picker.options.minDays = d1.getDay() === 0 ? 7 : 3;
       // render calendar with new options
       picker.render();
    });
  }
})
```

**Comment by adamboother** [comment]
Perfect, thanks very much
