### ISSUE TITLE
setDateRange(...) can set unavailable ranges

### ISSUE THREAD

**Issue by strarsis** [wakirin/Litepicker#143]
**Describe the bug**
`setDateRange(...)` sets a range in calendar that can't be set by user.

**To Reproduce**
1. Declare a calendar with a non-selectable range.
2. Invoke `setDateRange(...)` on the calendar that selects a part or the whole non-selectable range.
Notice that the range is selected, although it shouldn't.

**Expected behavior**
The range shouldn't be selected. Or at least only the part that is selectable.
Alternatively,, a `force` parameter could be offered that forces a selection despite not being selectable by user.

**jsfiddle.net / codepen.io / etc**
https://jsfiddle.net/mx27n8qz/8/

**Comment by wakirin** [comment]
v2.0.5

Added `force` argument.

https://litepicker.com/docs/methods#setdate
https://litepicker.com/docs/methods#setdaterange
