### ISSUE TITLE
OnSelect event not triggered on delete

### ISSUE THREAD

**Issue by seveneye** [wakirin/Litepicker#144]
**Describe the bug**
As far as I know, change event is handled in onSelect event. When deleting the value of the textbox, the onSelect event is not fired.

**To Reproduce**
1. Select a date
2. Delete date
3. onSelect event is not fired

**Expected behavior**
An event should be fired when the value is deleted

**Comment by wakirin** [comment]
Have you tested with `autoRefresh` option enabled ?

**Comment by seveneye** [comment]
@wakirin still not triggering the event.

However, I handled it by manually creating change event handler on the datepicker input. 

I suggest to trigger the change event when the input autocorrects, lets say user delete some characters and datepicker "corrects" the date, then trigger the change event so that custom event handlers can catch the it.
