### ISSUE TITLE
OnShow event we should get the position above or below the input of the calendar

### ISSUE THREAD

**Issue by zellerbaptiste** [wakirin/Litepicker#145]
When there isn't enough space below the input date or trigger element the calendare is shown above the trigger.
There isn't anyway to know where is placed the calendar.

My purpose would be to attach an arrow in CSS on the calendar's container and I need to know its position.
Can you add an attribute for example  `calendarPostition: top` on the event OnShow.

Or if it's not possible can you add an option on the public api like `forceBelowCalendar: true` to disable the changing position of the calendar and always force it to appear below the trigger element ?

**Comment by wakirin** [comment]
Added in v2.0.5

https://litepicker.com/docs/options#position-205

@zellerbaptiste 
in your case you can use `position: 'bottom'`.

_I know the thread is old, perhaps in the future someone will need it._

**Comment by Saltibarsciai** [comment]
I use 1.x, however upgrading to 2.x would require time, so I'll wait  till it matures and also date day click event is not added in new version, so no bigger need.

For 1.x workaround is just to overwrite default top class:
`.litepicker{top: 1559px !important;}`
