### ISSUE TITLE
disallowLockDaysInRange does not take into account disableWeekends true and proposed disableDays merge

### ISSUE THREAD

**Issue by ninetyninew** [wakirin/Litepicker#147]
**Describe the bug**
If you use the disableWeekends option then weekend dates are shown as locked but if you are also using the disallowLockDaysInRange option you can still select a range of dates including the weekend days.

This is also the same for the proposed disableDays option: https://github.com/wakirin/Litepicker/pull/128/files

**To Reproduce**
1. Set disableWeekends to true
2. Set disallowLockDaysInRange to true
3. Select a date range from Fri to Mon (so it includes the locked weekend dates)
4. Date range can be selected even through weekend locked

**Expected behavior**
Range unable to be selected as the dates within it are locked.

**Comment by wakirin** [comment]
https://wakirin.github.io/Litepicker/docs/options#lockdaysfilter-200
