### ISSUE TITLE
Month and Year dropdowns

### ISSUE THREAD

**Issue by ThePhoenixBird** [wakirin/Litepicker#15]
**Is your feature request related to a problem? Please describe.**
Not a problem, but the now deprecated Lightpick supported the option dropdowns where you could customize these items behaviour, and also to have select dropdowns to easily switch between large date periods.

**Describe the solution you'd like**
Port the dropdowns option from Lightpick to Litepicker

**Describe alternatives you've considered**
None

**Additional context**
Thanks for your great datepicker lib.

**Comment by wakirin** [comment]
New option `dropdowns` added in v1.0.20

**Comment by xaddict** [comment]
@wakirin additional subrequest to add the classes 'year' and 'month' to the respective dropdowns so they can easily be styled :)

**Comment by wakirin** [comment]
@xaddict 
from v1.0.22 these classes are added: 
`.month-item-name`
`.month-item-year`

**Comment by kl3sk** [comment]
Any way to add class instead (or choose between or both) instead of use predefined class ?

to be clear, I want to use bootstrap classes or and other JS plugin for dropdown (select)
