### ISSUE TITLE
Add event which would emit info about check-in and check-out date

### ISSUE THREAD

**Issue by Saltibarsciai** [wakirin/Litepicker#150]
**Is your feature request related to a problem? Please describe.**
the `onHover` event is not sufficient. If I want to change data based on first and second day selected, for example outside datepicker and can't do that with "attributes" passed in `function(date, attributes)` on `hover` event.

On mobile it is even worse because when you click on day item, attributes only give "day-item" without "is-start/end-date"

**Describe the solution you'd like**
I want new event `onClick: function(date, oldAttributes, newAttributes). I want new and old attributes because when second date is clicked on mobile it's `day-item` and after click it's also `is-end-date`

**Describe alternatives you've considered**
I tried using existing `onHover` event, but encountered many bugs in this hacky way and codes becomes bloated with validations and skip variables. `OnClick` event should really be there

**Additional context**
after first click on day item I want to add text under datepicker `dateOne - check-out-date` and after second day clicked `dateOne - dateTwo`
![Screenshot_19](https://user-images.githubusercontent.com/57238127/101015492-2e0ac880-3570-11eb-85a8-3e38c9daba63.png)

**Comment by aardbei2** [comment]
+1 would be great!

**Comment by wakirin** [comment]
https://wakirin.github.io/Litepicker/docs/events#preselect
