### ISSUE TITLE
Intl for "format" option

### ISSUE THREAD

**Issue by acoquoin** [wakirin/Litepicker#152]
**Is your feature request related to a problem? Please describe.**
Need to use [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) for "format" option based on document lang attribute.

**Describe the solution you'd like**
A best way to implements this, is (i think) to provide a callback for "format" option (with date(s) in parameter(s)) or to change the library to support [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) format output.

**Describe alternatives you've considered**
Make a fork and maybe a PR.

**Related to**
#136

**Comment by wakirin** [comment]
Unfortunately, Intl does not support parse, so we have to parse the Intl output ourselves.
With v2 is possible to use an external library for parse / output.

https://wakirin.github.io/Litepicker/docs/options#format
