### ISSUE TITLE
Safari error

### ISSUE THREAD

**Issue by carlosgp1401** [wakirin/Litepicker#153]
hi, in safari browser I have an error in the calendar.
<img width="684" alt="Captura de Pantalla 2020-12-17 a la(s) 20 15 08" src="https://user-images.githubusercontent.com/61802329/102555452-92b44000-40a5-11eb-8101-97a04ca4d95f.png">

**Comment by scott-fisher-iii** [comment]
I just checked my implementation in Safari and I'm not seeing that behavior. What is your setup?

**Comment by carlosgp1401** [comment]
In the demo shown in the project documentation. Browser Safari. [Demo](https://jsfiddle.net/waki/td0uapeo/)

**Comment by wakirin** [comment]
<img width="908" alt="Screen Shot 2021-01-20 at 19 03 53" src="https://user-images.githubusercontent.com/7056055/105178449-3e8ff600-5b52-11eb-965e-fcb3802e9560.png">

I don't see the problem.
Which version of Safari are you using?
