### ISSUE TITLE
Min Day per day

### ISSUE THREAD

**Issue by yashiroiori** [wakirin/Litepicker#154]
Hi, good plugin

How do to set minDays per day??
In my case I need set every Friday set minDays=2 to select Friday and Saturday in all weeks and all other days can select min 1 day

Thanks.

**Comment by wakirin** [comment]
With v2 and [lockDaysFilter](https://wakirin.github.io/Litepicker/docs/options#lockdaysfilter-200)

```js
new Litepicker({
	element: document.getElementById('datepicker'),
        singleMode: false,
        selectForward: true,
        lockDaysFilter: (d1, d2, pickedDates) => {
  	  if (pickedDates.length === 1) {
    	     const d = pickedDates[0].clone();
      
             if (d.getDay() === 5 && d.toDateString() === d1.toDateString()) {
      	       return true;
             }
      
            return false;
         }
       }
})
```

https://jsfiddle.net/6em3vxo5/
