### ISSUE TITLE
Date preview format

### ISSUE THREAD

**Issue by nikkii94** [wakirin/Litepicker#155]
**Is your feature request related to a problem? Please describe.**
I would like to display the selected date range in a different format in the date preview (near the buttons).
I'm using YYYY. MMM. DD format in the input, but I'd like to display the selected dates in YYYY-MM-DD format near the apply button.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/16080122/103464786-9fd45e80-4d36-11eb-99c5-557c3a22a7fc.png)

**Comment by wakirin** [comment]
With v2 and preselect event you can do something like this:
```js
  singleMode: false,
  autoApply: false,
  setup: (picker) => {
     picker.on('preselect', (d1, d2) => {
    	const preview = picker.ui.querySelector('.preview-date-range');
        preview.innerText = `${d1.format('D MMM YYYY')} - ${(d2 ? d2.format('D MMM YYYY') : '...')}`
    });
  }
```
