### ISSUE TITLE
elementEnd and scrollToDate, a month goes back

### ISSUE THREAD

**Issue by logan-19** [wakirin/Litepicker#156]
Hi, please tell me, if enabled
```
elementEnd: ...,
numberOfMonths: 2,
numberOfColumns: 2,
scrollToDate: true
```
after selecting date range, when I click in the field `element` I get the correct location of the months, but
when clicking in the field `elementEnd` I get a shift one month goes back, this happens when `scrollToDate` is set true
How to fix it?

![60460440630](https://user-images.githubusercontent.com/28824929/103467183-5ee34680-4d44-11eb-8952-71638f81887a.PNG)

eg.
[https://jsfiddle.net/2x1atqvg/](https://jsfiddle.net/2x1atqvg/)

**Comment by wakirin** [comment]
fixed in v2.
