### ISSUE TITLE
First is-booked in range disables itself when an available date is selected

### ISSUE THREAD

**Issue by digitalredefned** [wakirin/Litepicker#159]
This is on 1.5.7 from the CDN...

- Date range selection
- Booked dates defined in an array
- Go to March/April view
- Note the first dates in the booked(disabled) date ranges
- Click on an available date
- First dates in the booked date ranges are all of a sudden enabled

https://jsfiddle.net/e7ntyzo0/

https://www.loom.com/share/cdf8569285494e1ea888db95559d7cad

Thanks!
Jim

**Comment by wakirin** [comment]
Perhaps the option `lockDays` will help with this.

https://jsfiddle.net/sod3cerw/

**Comment by digitalredefned** [comment]
It's interesting how that the issue doesn't occur with that setting however that's not the user experience that my clients want.  The user cannot select backward and would have to close/reopen to reselect.

**Comment by wakirin** [comment]
Use `selectForward: false` if you need to select backward, in the example it is `true` because `hotelMode` is enabled.
That is why I removed this option (`hotelMode`) in v2, because there are many cases for hotels and this option is misleading.

**Comment by digitalredefned** [comment]
Now this does work for me.  I agree it is a bit confusing and combining these is a good move.  I didn't relate the lockedDays to my use case so consider that in the documentation.

Just to summarize

Kept - hotelModel: true
Replaced - lockDays in place of bookedDays
Added - disallowLockDaysInRange: true,
Added - selectForward: false so that user can select in either direction

I don't know if it's me but the calendar performance seems to be a little better as well.  It's a little bit snappier selecting.
