### ISSUE TITLE
How can I change the date picker language?

### ISSUE THREAD

**Issue by mickeychu** [wakirin/Litepicker#16]
Hi @wakirin ,

How can I change the language to Finnish?

I tried : `lang: 'fi_FI'` but got this error: 

![Screenshot 2019-12-23 at 17 08 24](https://user-images.githubusercontent.com/7807777/71365179-e2515000-25a6-11ea-8df6-b30f5ebe6076.png)

am I missing something?

**Comment by wakirin** [comment]
Hi @mickeychu ,
use `fi-FI` (with hyphen, not underscore).

**Comment by mickeychu** [comment]
Ohhh, my bad. Thank you!!!!!
