### ISSUE TITLE
Mobile-Device Bug - Android

### ISSUE THREAD

**Issue by jac1202** [wakirin/Litepicker#160]
**Describe the bug**
The error happens on Android mobile devices. If you first click in a text field and then click on the input field to which the picker is linked, the picker opens like in the desktop version.

**To Reproduce**
![mobileBug](https://user-images.githubusercontent.com/77626968/104927281-83c0f600-59a1-11eb-99a2-cbcd33ab87e6.gif)
The GIF shows the error. 
First the text field (firstDay) is clicked and then the input field of the picker is clicked -> The picker is displayed incorrectly.
The next click closes the picker.
The picker is then opened directly -> The picker opens in a popup (as it should be)

**Expected behavior**
If a text field was selected first, the picker should still open in a pop-up

**Comment by wakirin** [comment]
I tested on a real device (Android 10, Chrome 87.0.4280.141), the problem is not reproduced.
Possibly dependent on Android version or browser.

**Comment by jac1202** [comment]
Thanks for your answer.
I also reproduced it using Browser Stack <https://www.browserstack.com/>
and Saucelabs <https://saucelabs.com/>.Your GitHub repository says that you
also tested it with Browser Stack. Maybe you can reproduce the bug with it?
(The Bug is also reproduced on real devices e.g. Samsung Galaxy S8 Chrome
Version 87.0.4280.141 Android Version 9)
Thanks for your help!

Am Di., 19. Jan. 2021 um 09:49 Uhr schrieb Rinat G. <
notifications@github.com>:

**Comment by wakirin** [comment]
> GitHub repository says that you also tested it with Browser Stack.

Well, I have not tested on mobile devices.
As you can see there is no information about «Mobile» or «Android / iOS».

I have prepared a page showing why it is happening: https://dev.lvl.ninja/litepicker/issue-160.html
When you click to textfield the current orientation is displayed.
I don't know why `window.matchMedia('(orientation: portrait)').matches` doesn't correct work after focus from another text field.
Perhaps I will include [experimental](https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation) `window.screen.orientation` with a fallback `window.matchMedia('(orientation: portrait)').matches` for unsupported devices.

**Comment by jac1202** [comment]
That would be great! Thank you very much for your help!

Am Do., 21. Jan. 2021 um 08:56 Uhr schrieb Rinat G. <
notifications@github.com>:

**Comment by wakirin** [comment]
2.0.0-beta.1 fix this problem.
https://dev.lvl.ninja/litepicker/issue-160-2.0.0-beta.1.html

Thanks for report. 
Nice catch!
