### ISSUE TITLE
Better accessibility, replacing a[href="#"] with button etc.

### ISSUE THREAD

**Issue by evromalarkey** [wakirin/Litepicker#162]
**Is your feature request related to a problem? Please describe.**
Using a[href="#"] on all clickable elements can be problematic, for example when using litepicker with [swup](https://swup.js.org/), all links are acting as pages so I have to remove the href attribute from all elements with onRender event. 

**Describe the solution you'd like**
Replacing a[href="#"] with button[type="button"] would be the best, it's also more accessible, for individual dates div would suffice I think.

Also consider adding some more accessible attributes, like tabindex, aria-label etc.
here is good accessibility example (using keyboard is simple here) https://material.angular.io/components/datepicker/overview

**Comment by scott-fisher-iii** [comment]
I do agree that the buttons over anchors is a consider improvement for accessibility with the WCAG standards.
Anchors are fine for page redirects, but buttons are preferred whenever staying on the present page/view.

**Comment by wakirin** [comment]
https://wakirin.github.io/Litepicker/docs/plugins#keyboard-navigation-plugin
