### ISSUE TITLE
Using DateTime functions

### ISSUE THREAD

**Issue by evromalarkey** [wakirin/Litepicker#163]
**Describe the solution you'd like**
Would be possible to access the internal DateTime functions so there is no need to load external libraries for date operations?
Exporting it in index.ts should do the trick?

**Comment by wakirin** [comment]
Starting from v2 there will be the following changes:
Events `onSelect`, `onSelectEnd`, `onSelectStart` will return DateTime object. 
Who needs  Date object can use `date.getDateInstance()`. 

Also planned to add `DateTime` as function to picker.
Eg.:
```
const picker = new Litepicker({ ... });

picker.DateTime(); // return DateTime object
// or
picker.DateTime(someDateObject); // also return DateTime object based on provided Date object
```

**Comment by wakirin** [comment]
https://wakirin.github.io/Litepicker/docs/methods#datetime-200
