### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by devhoussam** [wakirin/Litepicker#165]
I have some issue in **GoogleDev Tool Console** it display this error message 

`Uncaught TypeError: Cannot read property 'dataset' of null
`

**app.js**

```
import Litepicker from 'litepicker';

jQuery(document).ready(function($) {
	"use strict";
	
    // -----------------------------
    //  Datepicker
    // -----------------------------
	
	var picker = new Litepicker({
		element: document.getElementById('litepicker'),
	});

});
```

**index.html**

`<input type="text" id="depart-date litepicker" class="form-control">`

**Comment by wakirin** [comment]
element: document.getElementById('**litepicker**'),

id="**depart-date litepicker**"

Set correct `id`.
