### ISSUE TITLE
NuxtJS/Vue implementation

### ISSUE THREAD

**Issue by leads** [wakirin/Litepicker#166]
Hi.
Trying to put this plugin in a NuxtJS project.

If I import it `import Litepicker from 'litepicker'` then the application hangs and eventually the error is 'Window is not defined'

If I add it as a plugin

```
//plugins/litepicker.js
import Vue from 'vue'
import Litepicker from 'litepicker'

Vue.use(Litepicker)
```

 ```
//nuxt.config.js
plugins: [
     { src: '~/plugins/litepicker.js', mode: 'client' }
  ],
```

it errors on
`Uncaught TypeError: Cannot set property 'options' of null`

Not sure where to go from here.

**Comment by wakirin** [comment]
Hi,
Could you try with v2 ?

```bash
npm i litepicker@2.0.0-beta.5
```

**Comment by wakirin** [comment]
I've tested with litepicker@2.0.0-beta.5

```js
// nuxt.config.js
  plugins: [
    { src: '~/plugins/litepicker.js', mode: 'client' }
  ],
```

```js
// index.vue
export default {
  mounted: function () {
    new Litepicker({
      element: document.getElementById("datepicker"),
    });
  },
};
```

It works.

**Comment by leads** [comment]
Will try that asap.

Does it work with a `yarn generate` ? I need to create a static html page.

**Comment by wakirin** [comment]
Yes, it [works](https://dev.lvl.ninja/litepicker/nuxtjs/).

**Comment by wakirin** [comment]
https://wakirin.github.io/Litepicker/docs/examples#how-to-add-litepicker-to-nuxtjs-

**Comment by leads** [comment]
Sorry for the delay. Just to confirm that the above works fine. Thanks.
