### ISSUE TITLE
Add option for x day "periods" within min/max days

### ISSUE THREAD

**Issue by ninetyninew** [wakirin/Litepicker#167]
If we want a user to be able to select a 7 day period we can use min and maxDays of 7 to do this but this limits to only 7 days as a maximum. So let's say we want to allow the user to select more than a single 7 day period. So a user could pick either 1st to 7th or 1st to 14th. Right now we could only set min and max days to 14 which in effect allows them to select 10 days whereas we want to only allow them 7 or 14.

Unless I'm missing a setting in the documentation I don't think this is possible right now?

**Comment by wakirin** [comment]
You can try do it with v2 and `lockDaysFilter`.

```js

new Litepicker({
	element: document.getElementById('datepicker'),
        singleMode: false,
	lockDaysFilter: (d1, d2, pickedDates) => {
		if (pickedDates.length === 1) {
                   const d7 = pickedDates[0].clone().add(6, 'day');
                   const d14 = pickedDates[0].clone().add(13, 'day');
        
                   return d1.toDateString() !== d7.toDateString() 
          	             && d1.toDateString() !== d14.toDateString();
               }
        
              return false;
       }
})
```

https://jsfiddle.net/9ux5r3h2/

v2 currently in beta.

**Comment by ninetyninew** [comment]
Thank you, do you have any pointers on how we could use this to work for any 7 day period, so we don't have to add each 7,14,21,28 condition? @wakirin

**Comment by wakirin** [comment]
https://jsfiddle.net/qx43jmnh/

I also used `selectForward`, if you want to allow selection backwards you need to adapt the current example.
