### ISSUE TITLE
Migrating from v1 to v2

### ISSUE THREAD

**Issue by wakirin** [wakirin/Litepicker#169]
## CDN URL CHANGED

```html
<script src="https://cdn.jsdelivr.net/npm/litepicker/dist/litepicker.js"></script>
```

### No CSS version:
```html
<script src="https://cdn.jsdelivr.net/npm/litepicker/dist/nocss/litepicker.js"></script>
```

Be careful, these links will return the latest version.  
To avoid breaking changes, you need to install a specific version.   
See [jsdelivr docs](https://www.jsdelivr.com/features#npm).

---

### In v2, these the following options methods and all events has been removed:
* Options `bookedDays `, `bookedDaysFormat`, `bookedDaysInclusivity`, `disallowBookedDaysInRange` - Since it duplicates `lockDays*` options.
* Option `anyBookedDaysAsCheckout` - Since v2.0.0 added option `lockDaysFilter`, we can use like this:
```js
lockDaysFilter: (date1, date2, pickedDates) => {
   if (pickedDates.length < 1) {
     // this example will disable weekends
     // define your own condition for indicate locked days
     const d = date1.getDay();
     return [6, 0].includes(d);
   }

   return false;
},
```
* Option `disableWeekends` - Since v2.0.0 added option `lockDaysFilter`, we can use like this:
```js
lockDaysFilter: (day) => {
   const d = day.getDay();

   return [6, 0].includes(d);
},
```
* Option `hotelMode` - The option `hotelMode` is misleading because there many cases for each hotel. The replacement is use option lockDaysFilter as a function and control the behavior you want.
* Option `moveByOneMonth` - Since v2.0.0 added new option `switchingMonths`. New option allow number, so you can set 1 or 2 or whatever you want.
* Options `resetBtnCallback`, `useResetBtn` - Since v2.0.0 added new option `resetButton`.
```js
...
resetButton: true,
...
// OR
...
// Do not need to call clearSelection inside this function.
// function should return HTML element
resetButton: () => {
   let btn = document.createElement('button');
   btn.innerText = 'Clear';
   btn.addEventListener('click', (evt) => {
     evt.preventDefault();

     // some custom action
   });

   return btn;
},
...
```
* All events (`onShow`, `onHide`, `onSelect`, `onError`, `onRender`, `onRenderDay`, `onChangeMonth`, `onChangeYear`, `onDayHover`, `onShowTooltip`) - Replacement is event emitter (see below).
* Method `setBookedDays(array)` - Since v2.0.0 there is no option `bookedDays`.

### These options has been updated:
* Option `format` - Since v2.0.0 option `format` support external library for parse/output.
Example with [luxon](https://moment.github.io/luxon/index.html):
```js
...
format: {
  // parse function should return Date object
  // date - Date object or string (perhaps there will be more types, need to check)
  parse(date) {
    if (date instanceof Date) {
      return date;
    }

    if (typeof date === 'number') {
      return new Date(date);
    }

    if (typeof date === 'string') {
      return luxon.DateTime.fromFormat(date, 'yyyy LLL dd').toJSDate();
    }

    return new Date();
  },

  // date - Date object
  // output function should return string
  output(date) {
    return luxon.DateTime.fromJSDate(date)
                        .toFormat('yyyy LLL dd');
  }
}
...
```

### These options, events and methods has been added:
* Option `resetButton` - Replacement for `resetBtnCallback` and `useResetBtn`.
* Option `switchingMonths` - Replacement for `moveByOneMonth`.
* Option `lockDaysFilter` - Mark locked days with custom function.
```js
lockDays: (date1, date2, pickedDates) => {
  // define your condition
  // 
  // date1 - start date or day of render ([DateTime](https://github.com/wakirin/Litepicker/blob/master/src/datetime.ts))
  // date2 - end date (DateTime)
  // pickedDates - number of selected days (Number)
  //
  // this function calling on render and after apply
  // thus, you need to check pickedDates.length, if it is:
  // 0 - no dates selected
  // 1 - selected start date
  // 2 - selected start and end dates

  // function should return Boolean, when true - day locked
}
```
* Option `tooltipNumber` - Allow to correct visible tooltip number.
```js
...
// days - number of selected days
// function should return Number
//
// shows one day less
tooltipNumber: (totalDays) => {
   return totalDays - 1;
}
...
```
* Method `DateTime` - return DateTime object.
```js
const picker = new Litepicker({ ... });

picker.DateTime(); // return DateTime object
// or
picker.DateTime(someDateObject); // also return DateTime object based on provided Date object
``` 
* Replacement for events.
Since v2 all events work with EventEmitter.
Example initialize:
```js
...
setup: (picker) => {
   picker.on('show', () => {
     // some action after show
   });

   picker.on('render', (ui) => {
     // some action after render
     // ui is root element of picker
   });
},
...
```
Event list:

- `.on('init', () => { ... });` - Event is called after initialization picker.
- `.on('before:render', (ui) => { ... });` - ui is root element of picker. Event is called before render function.
- `.on('render', (ui) => { ... });` - ui is root element of picker. Event is called after render function.
- `.on('render:month', (month, date) => { ... });` - month is element of rendered month. Event is called after renderMonth function.
- `.on('render:day', (day, date) => { ... });` - day is element of rendered day. Event is called after renderDay function.
- `.on('render:footer', (footer) => { ... });` - footer is element of rendered footer. Event is called after renderFooter function.
- `.on('change:month', (date, calendarIdx) => { ... });` - date is DateTime object of month, calendarIdx is index of calendar when splitView is enabled. Event is called after change month.
- `.on('change:year', (date, calendarIdx) => { ... });` - date is DateTime object of year, calendarIdx is index of calendar when splitView is enabled. Event is called after change year.
- `.on('error:range', () => { ... });` - Event is called on wrong selection range (when disallowLockDaysInRange is enabled).
- `.on('preselect', (date1, date2) => { ... });` - date1, date2 is DateTime object. Event is called on select days (before submit selection).
- `.on('selected', (date1, date2) => { ... });` - date1, date2 is DateTime object. Event is called when selection is submitted.
- `.on('button:cancel', () => { ... });` - Event is called after click on button cancel (footer).
- `.on('button:apply', (date1, date2) => { ... });` - date1, date2 is DateTime object. Event is called after click on button apply (footer).
- `.on('tooltip', (tooltip, day) => { ... });` - tooltip is element of tooltip, day is element of hovered day. Event is called after showTooltip function.
- `.on('before:show', (el) => { ... });` - el is triggered element. Event is called before show.
- `.on('show', (el) => { ... });` - el is triggered element. Event is called after show.
- `.on('destroy', () => { ... });` - Event is called after destroy.

Added plugins.  
See examples here: https://github.com/wakirin/Litepicker/tree/master/src/plugins  

[Documentation v2](https://wakirin.github.io/Litepicker/)

**Comment by arpowers** [comment]
Is there a way to add custom classes to the elements in the new version? Would be useful with TailwindCSS

**Comment by wakirin** [comment]
@arpowers you can use these events:

[render](https://wakirin.github.io/Litepicker/docs/events#render)
[render:day](https://wakirin.github.io/Litepicker/docs/events#renderday)
[render:month](https://wakirin.github.io/Litepicker/docs/events#rendermonth)

```js
new Litepicker({
  element: document.getElementById('datepicker'),
  setup: (picker) => {
    picker.on('render:day', (day) => {
      // add custom class to day element
      day.classList.add('some-custom-day-class');
    });

    picker.on('render:month', (month) => {
      // add custom class to button previous 
      month.querySelector('.button-previous-month').classList.add('some-custom-btn-class');
    });
  }
})
```

https://jsfiddle.net/bju4hwzt/

**Comment by arpowers** [comment]
@wakirin thanks! i'll give it a shot and let you know how it goes.

**Comment by kikky7** [comment]
I am using this datepicker with Laravel and Livewire and I need to preset date value (on edit), but init event is not working.

Here is the code (ignore the Laravel and Livewire stuff in code since they don't affect this issue):

```
<input type="text" autocomplete="off" {{ $attributes }} />

let currentDate = new Date();

new Litepicker({
    element: document.getElementById('datepicker'),
    setup: picker => {
        picker.on('init', () => {
            // This is not working
            console.log('init');
        });

        picker.on('selected', date => {
            // This is working and it sets date upon selected
            console.log('selected', date);
            @this.set("{{ $attributes->wire('model')->value }}", date.format('YYYY-MM-DD'))
        });
    }
});
```

When I am editing the form input, the value from object (wire:model) is visible in datepicker, but when I open and hide datepicker (without selecting any date) it "resets" to empty because date is not actually selected.
I need a way to preselect date if value exists, but init event is not working.

Version is 2.0.11
