### ISSUE TITLE
[TypeScript] Options come up as "any"

### ISSUE THREAD

**Issue by arpowers** [wakirin/Litepicker#170]
In the new version (2.0.1) the options for Litepicker come up as `any` which makes it a bit difficult to use TS for inline documentation.  I got around this by manually assigning the input to the `ILPConfiguration` type, but it seems fragile. 

<img width="1053" alt="Screen Shot 2021-02-01 at 12 09 41 PM" src="https://user-images.githubusercontent.com/308134/106506213-a1ed2280-6486-11eb-86df-782dd8a6d41f.png">

**Comment by wakirin** [comment]
Will be fixed in next release.

**Comment by wakirin** [comment]
fixed in 2.0.2
