### ISSUE TITLE
[ESM] No ES module export? 

### ISSUE THREAD

**Issue by arpowers** [wakirin/Litepicker#171]
We're using Vite for builds and it only supports ESM exports (and a very thin CJS compatibility)... 

Since we're going to attempt to use Tailwind to style Litepicker, we need to disable the native CSS. The `window` approach isn't working as far as we can tell. 

Anyway, we would use the "nocss" module but that one fails with Vite since it's a nested file. 

All would be solved if we could just import the ESM module directly but it looks like you only UMD and CJS builds. 

(If you're using Rollup adding ESM should be a simple fix.)

**Comment by wakirin** [comment]
> Anyway, we would use the "nocss" module but that one fails with Vite since it's a nested file.
>
> All would be solved if we could just import the ESM module directly but it looks like you only UMD and CJS builds.

Are you suggesting replacing "main" in package.json with the es module?
https://github.com/wakirin/Litepicker/blob/f56f7faaa8c919ca7565db5f8701c9dafcdd2e43/package.json#L5

**Comment by arpowers** [comment]
That's up to you, but you are assuming that webpack is in the stack and its days are numbered. 

I believe you can use `module`

**Comment by wakirin** [comment]
Perhaps the next major release will be target to ES6 (Of course, it won't be soon).
But I am not ready to change that at this time.

Thanks for the suggestion.

**Comment by brocgailit** [comment]
Why use standard ES modules (supported by all modern browsers) when we have webpack! /s

**Comment by rschristian** [comment]
> > Anyway, we would use the "nocss" module but that one fails with Vite since it's a nested file.
> > All would be solved if we could just import the ESM module directly but it looks like you only UMD and CJS builds.
> 
> Are you suggesting to add ES build and replacing "main" in package.json ?
> 
> https://github.com/wakirin/Litepicker/blob/f56f7faaa8c919ca7565db5f8701c9dafcdd2e43/package.json#L5

You shouldn't need to replace `"main"`. `"module"` or an export map would do the trick. Wouldn't be breaking. 

Mind if I write up a demo PR? Might be able to simplify your build process too with [`microbundle`](https://github.com/developit/microbundle) without losing any browser support.

**Comment by wakirin** [comment]
@rschristian 
If it is really possible to do it without breaking it, that would be great.
What's wrong with CSS ? Could you explain a little more?

**Comment by rschristian** [comment]
@wakirin 

Oh, nothing's "wrong" with it, but Microbundle only minimally processes CSS. A standalone CSS pipeline would needed with what you currently have.
