### ISSUE TITLE
disallowLockDaysInRange lets me select range with locked days

### ISSUE THREAD

**Issue by jbajou** [wakirin/Litepicker#172]
**Describe the bug**
When using `disallowLockDaysInRange: true`, I am able to select a range with locked days in between

**To Reproduce**
Create a LitePicker with 2 available dates in the same month for example. Select the first date, you can select the second as the end of the range, having only locked days in between.

**Expected behavior**
I would expect that `disallowLockDaysInRange` makes the user unable to select a range with locked days.

**Additional context**
I don't know if it helps to investigate, but I used lockDaysFilter to filter unavailable dates.

Thanks for the help in advance

**Comment by wakirin** [comment]
Option `disallowLockDaysInRange` does not affect to `lockDaysFilter`.
When using lockDaysFilter, you have to check the locked days yourself.
Example for locked weekends:

```js
lockDaysFilter: (date1, date2, pickedDates) => {

   while (date1.toJSDate() < date2.toJSDate()) {
     const day = date1.getDay();
     isWeekend = [6, 0].includes(day);
     if (isWeekend) { return true; }
     date1.add(1, 'day');
   }

   return false;
},
```

I will update docs on this.

**Comment by jbajou** [comment]
thanks for your fast feedback. Can you explain a bit the option `disallowLockDaysInRange` then ? I'm not sure I understand its purpose.
Args for `lockDaysFilter` make much more sense to me now ... :)

**Comment by wakirin** [comment]
@jbajou 

In v1.* no `lockDaysFilter` option.

So the `disallowLockDaysInRange` option is meant to be used with the `lockDays` option.
But starting with version 2 I added a new option `lockDaysFilter` for more flexible control of lock days with custom function.

Why does `lockDaysFilter` require `disallowLockDaysInRange: true` even though it doesn't disallow?

https://github.com/wakirin/Litepicker/blob/f56f7faaa8c919ca7565db5f8701c9dafcdd2e43/src/litepicker.ts#L194-L195

https://github.com/wakirin/Litepicker/blob/f56f7faaa8c919ca7565db5f8701c9dafcdd2e43/src/litepicker.ts#L146-L148

As you can see, this is required to start checking for lock days in ranges.

This option may need to be renamed.

**Comment by jbajou** [comment]
thanks for your lights mate. Highly appreciated it. I got it working as I needed. Cheers
