### ISSUE TITLE
Predefined ranges have 1 day too many

### ISSUE THREAD

**Issue by srichter** [wakirin/Litepicker#179]
**Describe the bug**
The predefined ranges for Last 7 and 30 Days actually select 8 and 31 days.

**To Reproduce**
1. Use the ranges plugin
2. Click on 'Last 7 Days'
 
**Expected behavior**
If today is February 8th, it should select a range of Feb 2 - Feb 8, for a total of 7 days inclusive. Instead, it selects Feb 1 - Feb 8, for a total of 8 days inclusive. 

This may not be a bug and may be intended behavior, but in my experience most times "Last 7 Days" will select a total of 7 days (and go from 6 days ago to today).

**Comment by wakirin** [comment]
Yes, good point.
I will fix it.

Thanks.

**Comment by wakirin** [comment]
fixed in 2.0.2
