### ISSUE TITLE
Changeover dates

### ISSUE THREAD

**Issue by vondam** [wakirin/Litepicker#183]
**Is your feature request related to a problem? Please describe.**

To be able to use Litepicker for the booking of apartments, I would like to request to add "changeover" dates to the calendar. The changeover days allow the user to select only specific dates for check-in or check-out. 

I'm currently using the options "lockDays" and "disallowLockDaysInRange" to prevent any collisions with bookings so I can't use this to lock certain days for the user to select.

Changeover days should be locked for selecting but could be in a certain daterange.

**Describe the solution you'd like**

I would like to have a similar solution to the "lockDays", just a second alternative I can use without the "disallowLocakDaysInRange".

**Describe alternatives you've considered**

At the moment I'm highlighting the changeover days so users know what days they can select. Validation is done after the users submits a request. I would like to let the user know before the submit a request.

**Additional context**

There's a jsfiddle for the example with highlighted changeover days;

[https://jsfiddle.net/mga5d2yL/](https://jsfiddle.net/mga5d2yL/)

P.s. I've read the following issue; [https://github.com/wakirin/Litepicker/issues/173](https://github.com/wakirin/Litepicker/issues/173) but I didn't want to contaminate the issue.

If there's anything I can do to help, let me know.

With best regards,

Kevin

**Comment by wakirin** [comment]
I see your example is using v1.4.7

In v2 I added new option `lockDaysFilter`.
You can do something like that:  https://jsfiddle.net/1o0c6gkp/

**Comment by vondam** [comment]
Sorry for the late response but thank you very much!
