### ISSUE TITLE
keyboard navigation change

### ISSUE THREAD

**Issue by leads** [wakirin/Litepicker#186]
Hi. Really liking the keyboard navigation plugin.

If I may make a suggestion - when the calendar opens, rather than focusing on the next/prev month, it goes straight into the days, so up/down can be used? See how https://www.kayak.co.uk/ does it.

Just an idea, thanks.

**Comment by wakirin** [comment]
https://litepicker.com/docs/plugins/keyboardnav/#firsttabindex-205

Use:
```js
  plugins: ['keyboardnav'],
  keyboardnav: {
    firstTabIndex: 2,
  },
```

https://jsfiddle.net/6voe2cta/
