### ISSUE TITLE
predefined ranges box is placed to the left of the input field

### ISSUE THREAD

**Issue by domi2120** [wakirin/Litepicker#189]
**Describe the bug**
When using the ranges plugin with the "left" position, the box displaying the predefined ranges is placed to the left of the actual date picker, which is aligned with the left border of the input field. This can cause it to reach outside of the visible window (https://jsfiddle.net/x1pj2zmy/4/). Before version 2 the box containing the predefined ranges started on the same vertical line as the input field being used, which ensured that the entirety of the DatePicker was visible if the input field was entirely visible.

**To Reproduce**
1. Go to https://jsfiddle.net/yr185jdw/
2. Click the input field
3. Look at the predefined ranges

**Expected behavior**
The left edge of the ranges box should be in line with the input field that the litepicker instance is using

**jsfiddle.net / codepen.io / etc**
https://jsfiddle.net/yr185jdw/

**Comment by wakirin** [comment]
Will be fixed in the next release.

**Comment by wakirin** [comment]
fixed in 2.0.7

https://jsfiddle.net/drveb8ko/
