### ISSUE TITLE
If date ranges allowed but if a minimum day of 1 is allowed allow apply dates button to be active

### ISSUE THREAD

**Issue by ninetyninew** [wakirin/Litepicker#192]
**Is your feature request related to a problem? Please describe.**
If date ranges are allowed but a user can also select just 1 day the user has to click twice on the 1 day to confirm the 1 day being selected. We though we could use autoApply: false to get around this but in that scenario they still have to click the 1 day twice as the apply button remains disabled.

**Describe the solution you'd like**
Apply button becomes active if one day clicked?

**Comment by wakirin** [comment]
Perhaps your issue related to #52 

I think in your case, you can do something like this:
https://jsfiddle.net/ouk763xn/
