### ISSUE TITLE
compare two date ranges on a single calendar

### ISSUE THREAD

**Issue by futwick** [wakirin/Litepicker#194]
Litepicker is excellent. Thank you for creating it.

It would be even better if it had the ability to compare two date ranges like the Google Analytics calendar can: 
![image](https://user-images.githubusercontent.com/790927/108876981-b55b5b80-75f6-11eb-8a95-549430c95f04.png)

**Comment by wakirin** [comment]
related to #21 

https://litepicker.com/docs/options#highlighteddays-114

**Comment by futwick** [comment]
I've found another workaround. I've made two transparent inline pickers and absolutely positioned one over the other.

![image](https://user-images.githubusercontent.com/790927/108896784-3e7d8d00-760d-11eb-9ac2-587703bf6ba1.png)


Not perfect but it has potential.

I'm switching between the two pickers by changing their z-index. 

I've had to make sure the two calendars stay in sync (when the month changes on one it must also change on the other).

I've made the following elements transparent.

.container__months background on both calendars:
`.litepicker .container__months {
    background-color: transparent;
}`

.day-item and .month-item-header text color _on the second calendar_:
`##picker2container .litepicker .container__days .day-item,  
##picker2container .litepicker .month-item-header {
	color: transparent;
	}`

**Comment by wakirin** [comment]
Nice, thanks for sharing the solution.
