### ISSUE TITLE
container__footer is to the right when using ranges

### ISSUE THREAD

**Issue by harrington101** [wakirin/Litepicker#196]
When using the ranges plugin, the container__footer is now forced to the right where in previously it was below the dates and ranges. In the previous version, container__predefined-ranges was inside of the container__main. 

To reproduce, create a range date picker with 2 months displayed, ranges, and apply/cancel buttons. 

**Expected behavior**
Footer should be at the bottom.

**Comment by wakirin** [comment]
fixed in 2.0.9
