### ISSUE TITLE
Sass vs postcss-nested?

### ISSUE THREAD

**Issue by pavelloz** [wakirin/Litepicker#2]
This is more of a question than anything - do you want to get rid of sass?
I see you used postcss for some things and sass for nesting - there is [postcss nested](https://github.com/postcss/postcss-nested) plugin that could do that and is much lighter.

node-sass has native c extensions that need to be recompiled every time you change your node, which is annoying - this part can be fixed by using `sass` instead of `node-sass` (read more: https://github.com/webpack-contrib/sass-loader#implementation )

I did this conversion once with much more complicated sass setup(s) and never regretted it.

**Comment by wakirin** [comment]
Thanks, I will read about it.
