### ISSUE TITLE
Mobilefriendly plugin: Add an option for the breakpoint

### ISSUE THREAD

**Issue by nyroDev** [wakirin/Litepicker#200]
I noticed the mobilefriendly activates itself only when the width (or height) is less than 480px.

As far as I understand, the related line is here:
https://github.com/wakirin/Litepicker/blob/master/src/plugins/mobilefriendly/index.js#L35

I was wondering if it was possible to add an option that let us define this 480px breakpoint.

In my usecase, it will allow me to reflet my mobile responsive breakpoints.

Thanks in advance

**Comment by wakirin** [comment]
Ok, I will add it as an option in the next release.

**Comment by wakirin** [comment]
v2.0.11

https://litepicker.com/docs/plugins/mobilefriendly/#breakpoint-2011

**Comment by nyroDev** [comment]
Wooh, that was fast!
Thank you!
