### ISSUE TITLE
setDateRange not working correctly in inline mode

### ISSUE THREAD

**Issue by evromalarkey** [wakirin/Litepicker#201]
**Describe the bug**
On setDateRange call I have to call also render method for the dates change in inline mode. Expected behavior would be this working out of the box in inline mode, this might be problem with more methods and events.

**jsfiddle.net / codepen.io / etc**
https://jsfiddle.net/48p6fnxw/

**Comment by MrMarlow** [comment]
Can you explain the issue in some more detail. The current description is not very clear.

You mention a render method, but there is no render method called within the fiddle you provided.

**Comment by evromalarkey** [comment]
I mean calling picker.render() after setDateRange to update the calendar in inline mode. But  I would expect this to work without it

**Comment by wakirin** [comment]
@evromalarkey 
Ok, I understood.
In the next release you won't need to call extra `render` after `setDateRange` in inline mode.

**Comment by wakirin** [comment]
v2.0.11

https://jsfiddle.net/kjfyzq93/

**Comment by wakirin** [comment]
I think I was a little rushed with my decision.
I will revert these changes in the next release.
I think this looks like unexpected behavior of the `setDate` and `setDateRange` methods (these methods should only set the date, nothing else).

@evromalarkey 
So if you will use next release do not forget to call `render()` after calling `setDateRange`.
Or do not upgrade your version and use 2.0.11

**Comment by lubomirblazekcz** [comment]
Understood, but it's little confusing that after setting the date nothing happens. Maybe mention of this in the docs would help? Also render method is not documented there.

**Comment by wakirin** [comment]
@evromalarkey 
I can see that there is already an `updateInput` in `setDateRange` and I shouldn't delete it now because it will be breaking changes.
So I will do it in next major release (next major is not coming soon).
I was wrong, sorry for disturb.
You can still use any 2.+ version, it will include `render` method for `inlineMode`.
