### ISSUE TITLE
Leaving input field (blur) doesn't hide the calendar

### ISSUE THREAD

**Issue by nyroDev** [wakirin/Litepicker#203]
**Describe the bug**
When having multiple inputs of any sort and using the Tab key to go to the next field, the Calendar is not hidden.

**To Reproduce**
1. Go to https://codepen.io/nyroDev/pen/LYbJpqK?editors=1010
2. Click on the date field
3. It will show the calendar
4. Hit the "Tab key" in order to go to the text field
5. The Focus is now on the text field, but the calendar is shown above it

**Expected behavior**
When leaving an input field (blur), the calendar should disapear.

**Additional context**
I'm not using the range selection, so the blur binding might have side effect here that I'm not aware of.

**Comment by wakirin** [comment]
https://codepen.io/wakirin/pen/QWGVEMd?editors=1010

I will think about including it in the library.
This implementation may conflict with `keyboardnav` plugin.

**Comment by nyroDev** [comment]
Thanks for quick solution.
