### ISSUE TITLE
Hiding calendar when input text was cleared by the user reset the previous value

### ISSUE THREAD

**Issue by nyroDev** [wakirin/Litepicker#204]
**Describe the bug**
When input field is cleared by the user, the value is reset to the previous value when calendar is hidden.

**To Reproduce**
1. Go to https://codepen.io/nyroDev/pen/LYbJpqK?editors=1010
2. Click on the date field to show the calendar
3. Select a date
4. Click again on the date field, to show the calendar again
5. Clear the date field with the keyboard
6. Click anywhere on the page to hide the calendar

**Expected behavior**
When input field is cleared by the user, it should stay empty and not reset to previous value.

**Additional context**
I don't know if it's related to the onInput function that should set value to null, or the hide function that reset the value.
I tried to dig into the code a little bit, but I didn't have time to fork and build it on my computer yet.

**Comment by wakirin** [comment]
Temporary solution: https://codepen.io/wakirin/pen/MWbqeXr?editors=1010

I will include this fix in the next release.

**Comment by nyroDev** [comment]
Thanks again for your quick answer and solution.
