### ISSUE TITLE
Syntax error on IE11

### ISSUE THREAD

**Issue by dazgreer** [wakirin/Litepicker#207]
**Describe the bug**
I get a syntax error in IE11, it seems to be for the '=>' notation for Events. This is despite adding the IE11 polyfills. 
Note: When I remove these there is no error however the calendar does not display.

**To Reproduce**
1. Go to http://tsg.desiredigital.co.uk/litepicker-issue.html in IE11
2. Check console for syntax error

**Expected behavior**
No syntax error

**jsfiddle.net / codepen.io / etc**
http://tsg.desiredigital.co.uk/litepicker-issue.html

**Additional context**
The site uses requireJS which includes a script.js file that includes the code. This file has a require statement for the CDN version of the IE11 Polyfills before another require statement which includes all of the bundled plugins (including the litepicker.js file)

**Comment by wakirin** [comment]
<img width="742" alt="Screen Shot 2021-03-10 at 23 33 33" src="https://user-images.githubusercontent.com/7056055/110671870-391d6680-81f9-11eb-9c63-d122991858f9.png">

You don't have to use arrow functions if you want to support IE11.
Or use babel in your project.

You can see the docs in IE11: https://litepicker.com/
It works.

**Comment by dazgreer** [comment]
Thanks, I've got rid of the syntax error by changing the '=>' syntax.

The date picker is still not displaying in IE11 but I'm less concerned about that
