### ISSUE TITLE
Window is not defined ( NextJS )

### ISSUE THREAD

**Issue by christianto88** [wakirin/Litepicker#208]
Hello
I am trying to use the library on my nextJS project. and it seems after importing the library, it gives **window is not defined** error. 

I saw there is example for implementation in NuxtJS. Is there any way it can work with NextJS?

**Comment by wakirin** [comment]
```js
  componentDidMount() {
    if (typeof window !== 'undefined') {
      import('litepicker').then(({ Litepicker }) => {
        new Litepicker({
          element: document.getElementById('datepicker'),
          singleMode: false,
        })
      });
    }
  }
```

If you know a better way do it, share please your solution.
I will add an example for NextJS to the docs later.

**Comment by Mykel-E** [comment]
Please add this to the documentation already... It took me 2days to find the solution. 🙏🏼
