### ISSUE TITLE
Be able to select a second range of dates inside the picker

### ISSUE THREAD

**Issue by ThePhoenixBird** [wakirin/Litepicker#21]
**Is your feature request related to a problem? Please describe.**
Currently I'm developing metrics dashboards and I would like to avoid using two different datepickers to select comparison ranges in a interface, thus allowing to select two date ranges in just like Google Analytics does:

![Image](https://i.imgur.com/CFlI16G.png)

**Describe the solution you'd like**
Be able to bind a second pair of inputs to add a second date range to the date picker.

**Describe alternatives you've considered**
I have searched around and couldn't find anything else like this, Litepicker would be the first library to do this.

**Comment by xaddict** [comment]
Alternative Proposition to get this:

An option `highlightedDays: [['2019-12-01', '2019-12-31']]` which you can set the color of `--litepickerDayIsHighlightedBg`.
This way you can bind individual litepickers to the top and bottom dates (letting litepicker do what it does best) and use highlightedDays to show the dates you need.

Should be easy to wire up with the events and methods once this functionality is added.

**Comment by wakirin** [comment]
Thanks for suggestions.
I think @xaddict suggested a good way to achieve this.

**Comment by wakirin** [comment]
Added in v1.1.4

https://wakirin.github.io/Litepicker/#option-highlightedDays
