### ISSUE TITLE
Do you support hours, minutes, seconds

### ISSUE THREAD

**Issue by JangCool** [wakirin/Litepicker#213]
I think this is so good.
However, I can't see an example of selecting a time.
Are you not applying?

Is it not supported as in the image below?

image
![image](https://user-images.githubusercontent.com/2518021/111131365-8879e300-85bb-11eb-9859-17084acd73af.png)

**Comment by scott-fisher-iii** [comment]
This is a pending enhancement request already:
https://github.com/wakirin/Litepicker/issues/1

**Comment by wakirin** [comment]
duplicate of #1
