### ISSUE TITLE
Litepicker is not defined

### ISSUE THREAD

**Issue by shinally97** [wakirin/Litepicker#216]
**Download**
I downloaded Litepicker in order to use it on my site, using php and js.

**The file litepicker.ts has an error**
The error is: Property 'emit' does not exist on type 'Litepicker'

**Code for imports**
On js I'm using this: 
`<script src="{{ asset('lib/litepicker/src/index.ts') }}"></script>`
`<script src="{{ asset('lib/litepicker/dist/plugins/mobilefriendly/index.js') }}"></script>`

The "{{ }}" are **Twig** syntax, from **Symfony**

How can I solve this problem? the doc uses **import**s but they won't work

**Comment by craigengland** [comment]
Your first script tag looks as though it has a typo, `index.ts`. If you change that to `index.js` do you still get an error?

**Comment by wakirin** [comment]
There is no `litepicker/src/index.ts` or `litepicker/src/index.js` files.
It should be: `litepicker/dist/litepicker.js`

See: https://litepicker.com/#installation
