### ISSUE TITLE
Booked days in a range can still be selected as end date

### ISSUE THREAD

**Issue by xaddict** [wakirin/Litepicker#22]
NOTE: I have used the terms SHOULD and MUST NOT like I know they are being used in W3C documentation. I do not mean to sound condescending or belittling. I could never write anything like this and I love that this even exists without all the momentjs clutter :)

**Describe the bug**
`bookedDays` is a nice way to prevent people from selecting a booked day as a start point but still enable them to select that date as an end date.

However, when there is a range of booked dates (2020-02-04 - 2020-02-26), or separate but connected dates (2020-02-04, 2020-02-05, 2020-02-06) the user is able to select an end date within and over the booked date ranges.

**To Reproduce**
Go to https://codepen.io/xaddict/pen/oNgoojO
1. Choose the first of february 2020 as a start date
2. OR choose the last of february 2020 as an end date
3. Click somewhere in the disabled dates to set it as an end date 
4. OR click somewhere after/before the booked dates

**Expected behavior**
A selected range MUST NOT:
- bridge a booked range
- start inside of a booked range
- end inside of a booked range

So in the example "2020-02-04 to 2020-02-26 (exclusive) are booked":
- Selecting 2020-02-03 to 2020-02-04 SHOULD be possible
- Selecting 2020-02-03 to 2020-02-05 MUST NOT be possible
- Selecting 2020-02-04 to anything MUST NOT be possible
- Selecting 2020-02-10 to anything MUST NOT be possible
- Selecting 2020-02-26 to 2020-02-27 SHOULD be possible

`disallowLockDaysInRange` fixes this problem for `lockDays` but I don't think `bookedDays` should have a `disallowBookedDaysInRange` since it is the sole use case for `bookedDays`

**jsfiddle.net / codepen.io / etc**
https://codepen.io/xaddict/pen/oNgoojO

**Additional context**
Combining `bookedDays`, `lockDays` and `disallowLockDaysInRange` gets us nearer but comes with weird side effects like the range showing and then disappearing or setting to a different date when you click the end date because there are locked days in the range.

**Comment by wakirin** [comment]
Maybe in your case  is better to use only `lockDays` and `disallowBookedDaysInRange`.
```
lockDays: [['2020-02-05', '2020-02-26']],
disallowLockDaysInRange: true
```
As I can see, it is should covers all your examples:
- \[x] Selecting 2020-02-03 to 2020-02-04 SHOULD be possible
- \[x] Selecting 2020-02-03 to 2020-02-05 MUST NOT be possible
- \[x] Selecting 2020-02-04 to anything MUST NOT be possible
- \[x] Selecting 2020-02-10 to anything MUST NOT be possible
- \[x] Selecting 2020-02-26 to 2020-02-27 SHOULD be possible

**Comment by myraumhafen** [comment]
I use the calendar for renting an apartment. To lock the periods already booked, it works quite well with "lockdays", as you described it. But to stick to the examples why can't you book from 2020-02-03 to 2020-02-05? On 2020-02-05 the guest can normally only check in in the afternoon. So the night before can be used by another guest.

Guest 1 check-in: 2020-02-03 at the earliest 3 p.m.
Guest 1 check-out: 2020-02-05 latest 11 a.m.
Guest 2 check-in: 2020-02-05 at 3 p.m. at the earliest
Guest 2 Check-Out: 2020-02-26 latest 11 a.m.

I've already changed the code. But it's a complicated solution, since I'm not that good at TypeScript yet. I think you can probably solve this better with a new parameter :-) I would be happy about such an option. Thank you very much.

**Comment by wakirin** [comment]
Ok, I understood.
I will add one or two options to improve control of the option `bookedDays`.

**Comment by xaddict** [comment]
> Maybe in your case is better to use only `lockDays` and `disallowBookedDaysInRange`.
> 
> ```
> lockDays: [['2020-02-05', '2020-02-26']],
> disallowLockDaysInRange: true
> ```

At first it would seem that this is the solution but it has one problem that I forgot in my example:
If 2020-02-28 is booked (so someone's is staying the night of the 28th to the 29th):
with bookedDays I can select the 27 to 28 as an enddate (as expected) but I can also select 27 to 29 even though the 28th is fully booked so there's no more room. 
with lockDays I cannot select the 28th as start date (as expected) but can also not select it as an end date (unexpected)

**Comment by wakirin** [comment]
I thought about the option `bookedDays` and I think your way is correct.
From v1.0.22 I changed behaviors for options [hotelMode](https://wakirin.github.io/Litepicker/index.html#option-hotelMode) and [bookedDays](https://wakirin.github.io/Litepicker/index.html#option-bookedDays).

Now by default with enabled `hotelMode`:
* check-out date is available for select as check-in date 
* check-in date is available for select as check-out date

Here is an example: https://jsfiddle.net/crw1fzyo/

Anyone who needs to be allow to select any booked days as check-out date can use the new option [anyBookedDaysAsCheckout](https://wakirin.github.io/Litepicker/index.html#option-anyBookedDaysAsCheckout).

**Comment by xaddict** [comment]
Nice. Selecting through a range now works as expected...

There's one thing remaining I can't wrap my head around.

If the client arrives on the 10th and leaves on the 20th (so a booking from the 10th to 19th inclusive) I can now select the 19th as a start date.
Does that mean I have to add the 20th to the booking?

**Comment by wakirin** [comment]
Yes, required a range from check-in to check-out dates.
If you wish you can set a range only inclusive dates (your example from 10th to 19th), but then you need to add option `bookedDaysInclusivity: '[]'` ([docs](https://wakirin.github.io/Litepicker/index.html#option-bookedDaysInclusivity)) and then last date in a range will be unavailable for selecting.

**Comment by xaddict** [comment]
Thanks so much!
