### ISSUE TITLE
Calendar won't show

### ISSUE THREAD

**Issue by thmasker** [wakirin/Litepicker#23]
Hello, I'm just trying your calendar along with bootstrap 4, and simply the calendar won't show up when its cell is clicked.

I have the following under `head` section (maybe the order matters?...):

```
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js"></script> 
    <script src="https://cdn.jsdelivr.net/npm/litepicker/dist/js/main.js"></script>
</head>
```
and its `body` related part:

```
<div id="body" class="container">
    <table class="table table-striped" style="margin-top:50px;">
        <tr>
	    <td>
	        <input type="text" id="dates">
	    </td>
        </tr>
    </table>
</div>
```
Finally, the JS code is the following:

```
var picker = new Litepicker({
    element: document.getElementById('dates'),
    format: 'YYYY-MM-DD',
    lang: 'es-ES',
    singleMode: false
});
```

**Comment by wakirin** [comment]
Hi,
I don't see any problems https://jsfiddle.net/Lh2nmxre/
Make sure you js code is execute.

**Comment by thmasker** [comment]
> Make sure you js code is execute.

How could I check that??

**Comment by wakirin** [comment]
You can add `console.log('qwerty')` above your js code.
After loading page check the browser console.

I forgot to ask, where you are run js code in `head` or `body` sections ?
Do you have any errors in the browser console ?

**Comment by thmasker** [comment]
No errors, and I'm running it in the `body`. It seems to execute the script, too.

Could it be something about the table, which is dynamically implemented through Bootstrap 4?

**Comment by myraumhafen** [comment]
I also had some problems with bootstrap. Bootstrap uses the box-sizing attribute. As a result, the calendar was not displayed correctly for me. You should deactivate box-sizing for the calendar. Maybe that's the problem.
My solution in the style sheet looks like this. This deactivates box-sizing for the calendar display:

```
.month-item {
   -webkit-box-sizing: content-box! important;
      -moz-box-sizing: content-box! important;
           box-sizing: content-box! important;
}
.month-item: before,
.month-item: after {
   -webkit-box-sizing: content-box! important;
      -moz-box-sizing: content-box! important;
           box-sizing: content-box! important;
}
```

**Comment by thmasker** [comment]
> ```
> .month-item {
>    -webkit-box-sizing: content-box !important;
>       -moz-box-sizing: content-box !important;
>            box-sizing: content-box !important;
> }
> .month-item: before,
> .month-item: after {
>    -webkit-box-sizing: content-box !important;
>       -moz-box-sizing: content-box !important;
>            box-sizing: content-box !important;
> }
> ```

Oh, nice. What style sheet are you referring to? Because I only use the default Bootstrap one, which I have not downloaded.

**Comment by wakirin** [comment]
@thmasker show more code if you can.

**Comment by thmasker** [comment]
Ok, I've just created a repository where you can see the whole project as is:

https://github.com/thmasker/practicas_interactivos

**Comment by wakirin** [comment]
I think you should init Litepicker after render, try this example: https://stackoverflow.com/a/19941134

**Comment by myraumhafen** [comment]
> > ```
> > .month-item {
> >    -webkit-box-sizing: content-box !important;
> >       -moz-box-sizing: content-box !important;
> >            box-sizing: content-box !important;
> > }
> > .month-item: before,
> > .month-item: after {
> >    -webkit-box-sizing: content-box !important;
> >       -moz-box-sizing: content-box !important;
> >            box-sizing: content-box !important;
> > }
> > ```
> 
> 
> Oh, nice. What style sheet are you referring to? Because I only use the default Bootstrap one, which I have not downloaded.

You can simply create your own stylesheet with these specifications and insert it behind the bootstrap stylesheet in your html document.

**Comment by thmasker** [comment]
> I think you should init Litepicker after render, try this example: https://stackoverflow.com/a/19941134

This solution doesn't seem to work either.

**Comment by thmasker** [comment]
> ```
> .month-item {
>    -webkit-box-sizing: content-box !important;
>       -moz-box-sizing: content-box !important;
>            box-sizing: content-box !important;
> }
> .month-item: before,
> .month-item: after {
>    -webkit-box-sizing: content-box !important;
>       -moz-box-sizing: content-box !important;
>            box-sizing: content-box !important;
> }
> ```

Doesn't seem to work either

**Comment by wakirin** [comment]
@thmasker 
Example with knockout, as I told above you should create Litepicker after render the table.

https://jsfiddle.net/wujx9cz6/

**Comment by thmasker** [comment]
```
knockout-min.js:73 Uncaught ReferenceError: Unable to process binding "foreach: function(){return { data:buildings,afterRender:onAfterRender} }"
Message: onAfterRender is not defined
```

I put it exactly like you have in the example. I upload it to the repo.

**Comment by wakirin** [comment]
You can't just copy-paste the example and hope that is works.
I showed you an example of working knockout.js, but you have to adapt it for your project yourself.
I close this issue, because it is not problem of Litepicker.

**Comment by thmasker** [comment]
Well, I obviously tried to adapt it, but I'm no html nor javascript expert, I'm doing my best. Anyway thanks for trying to help
