### ISSUE TITLE
Example with Angular Reactive form

### ISSUE THREAD

**Issue by sewalsh** [wakirin/Litepicker#24]
Hi there,

Does anyone have an example of this with an Angular Reactive Form?

I can get the calendar working but the date value isn't being passed back. As an aside, If I set my input field to type="date", I get two date pickers appearing (using FF).

My input in .html

```
<input
formControlName="startTime"
id="datepicker"
placeholder="Date"
class="w-10/12 sm:w-64 h-10 pl-4 border-2 rounded text-gray-800"
                  />
```

**Comment by wakirin** [comment]
Hi,
provide an example on jsfiddle.net please.
Thanks.
