### ISSUE TITLE
Two input field + mobile => not always the appropiate date is replaced

### ISSUE THREAD

**Issue by lesda** [wakirin/Litepicker#25]
Having a setup where you have both 'element' and 'elementEnd' configured, 'allowRepick' enabled and you are on mobile, the repick is not working correctly. Not the clicked element's value will be replaced but the initially bigger value.
Also if you disable the 'allowRepick' then - by design - you always have to select two dates, but in the previously mentioned setup, also only on mobile, the selector closes after the first click, replacing the biggest date, while keeping the smaller one.

I was trying to figure it out, but no luck yet. My best guess is that the onMouse event handlers are the key as they don't activate on mobile environment, Maybe this is causing the issue.

**Comment by wakirin** [comment]
Should be fixed in v1.0.27 (just now published).
Thanks for information.

**Comment by lesda** [comment]
Wow, that was fast. Thanks.
