### ISSUE TITLE
Two input field + preselected long daterange + endDate clicked => not the best fit upon showing the calendar

### ISSUE THREAD

**Issue by lesda** [wakirin/Litepicker#26]
If you have both 'element' and 'elementEnd' used, numberofMonths set to at least two, dates are already set in a way that the two date doesn't belong to the same month. If at this point you click on 'elementEnd' than the end of the date range will be in the first month's slot, not displaying the beginning of the range.
In general, it would be the best user experience to use the first month's slot in case the 'element' was clicked and use the last month's slot in case the 'elementEnd' was clicked. That way - in most cases - the full preselected date range will be visible upon showing the calendar. 

It's a borderline bug/feature request.

**Comment by wakirin** [comment]
Changed from v1.0.29
Example: https://jsfiddle.net/on9f1kr4/
