### ISSUE TITLE
newDate option seems to set date to tomorrow not today?

### ISSUE THREAD

**Issue by adam-jones-net** [wakirin/Litepicker#262]
in my configuration to setup the calendar I use the option

`minDate:  new Date(),`

And yet todays date isn't selectable in the resulting calendar, only the day after today as a starting date is possible.      Am I doing something wrong ?

**Comment by devinemke** [comment]
i had the same issue, and was able to solve by passing a date string (format **YYYY-MM-DD**) rather than a JS Date Object. in my case i needed users to select a date between now and the 3 months from now. escaping out of JS with PHP:
```
const picker = new Litepicker({
	element: document.getElementById("date"),
	minDate: "' . date('Y-m-d') . '",
	maxDate: "' . date('Y-m-d', strtotime('+3 months')) . '"
});
```
hope this helps.

**Comment by adam-jones-net** [comment]
Thanks @devinemke yes that did it!
