### ISSUE TITLE
<Date Range Picker> delimiter display 

### ISSUE THREAD

**Issue by mahns1201** [wakirin/Litepicker#266]
**Is your feature request related to a problem? Please describe.**
First of all Thank you for providing this awesome service.

but i got a small problem when i use <Date Range Picker> on set delimiter
I want to change delimiter display on select box
It seemed to be fully operational until the apply button was pressed.
I might be doing something wrong.

Here is my code and display 

```
<Litepicker
      v-model="daterange"
      :options="{
        autoApply: false,
        format: 'YYYY-MM-DD',
        delimiter: ' ~ ',
        singleMode: false,
        numberOfColumns: 2,
        numberOfMonths: 2,
        showWeekNumbers: true,
        dropdowns: {
          minYear: 1990,
          maxYear: null,
          months: true,
          years: true,
        },
      }"
  class="form-control w-56 block mx-auto"
/>
```
<img width="694" alt="스크린샷 2021-09-15 오전 11 42 22" src="https://user-images.githubusercontent.com/46416816/133361759-e70c7f96-a947-4de7-9aa8-31f3b9bd85e6.png">

<img width="258" alt="스크린샷 2021-09-15 오전 11 42 40" src="https://user-images.githubusercontent.com/46416816/133361769-57531d5a-19a0-4e67-898c-7dbf5f111545.png">

As you can see, the delimiter is set ' ~ ' but the display's delimiter is still ' - ' after apply
Thank you.

**Comment by sitenzo** [comment]
Hello @mahns1201,

Have you solved the problem yet.
Everything is working fine if i check it on [jsfiddle](https://jsfiddle.net/f1rk502m/2/)
Maybe your input is wrong?

**Comment by mahns1201** [comment]
@sitenzo
Thanks for the reply  :)

Maybe the setting of my project is wrong.
It hasn't been solved yet, but I'll study more.
