### ISSUE TITLE
Opening the calendar popup from an element other than the input

### ISSUE THREAD

**Issue by clselin** [wakirin/Litepicker#267]
I have been asked to implement some designs where the litepicker datepicker is launched on a click on an element that is not the actual text input element that displays the resulting date. Eg. there's a big button that say 'select your dates!' sitting next to the text input. I need the calendar to pop up whether the user clicks on the text input or my button. 

Reading the documentation, I couldn't see an option to set a selector for a calendar trigger, or a function i could call to open the calendar from an event listener elsewhere in my js. 

Alternately I've considered making my text input large, transparent, and on top of my button so that it can capture the click, but this has its own pitfalls, including hover CSS not working on the button, or keyboard navigation to the button not working. 

Is there a way to do this in litepicker I'm missing? Or is it a feature that could be added? 

Thanks!

**Comment by sitenzo** [comment]
Hello @clselin ,

Look at [methods#show](https://litepicker.com/docs/methods#show)

You can trigger a event like on button click somethin like this.

```
const picker = new Litepicker({ options });

jQuery('#ButtonID').on('click',function(){
     picker.show();
});
```

**Comment by bobmagicii** [comment]
that exact use case and solution worked great for me and seems reasonable enough of a solution.

[edit] tho to really polish it up, it will need a tweak to disable the forced onclick atm.
