### ISSUE TITLE
BookedDays appear/disappear

### ISSUE THREAD

**Issue by lesda** [wakirin/Litepicker#27]
Having configured the 'bookedDays' option with an array os dates, upon opening a calendar everything looks fine (the booked days are gray, others are black), but after choosing a first date (onMouseEnter starts to fire) the bookedDays are gone, every date is black.
The exclusions is checked, and after setting the date range everything is normal again, so probably during the renderDay is losing the is-booked class when called from onMouseEnter.

**Comment by wakirin** [comment]
You need to use the latest version, the behaviors of the options `hotelMode` and `bookedDays` has change in the latest version.
Discussion here #22

**Comment by lesda** [comment]
I'm using the latest version, 1.0.27, but I set the 'selectForward' to false, as I wanted to give the users more flexibility when there is already a daterange set and they just want to modify it.

**Comment by lesda** [comment]
I just check with setting 'selectForward' set to true, it doesn't change anything in terms of thus bug, it still happens. 

But it also introduces another one: if there is already a startData and endData then upon opening the calendar and hovering the mouse over any day that is before the original startData, the rangeselection and tooltip kind of freezes, stops responding to more mouse movements until the mouse leaves the whole calendar (than its back to normal).

**Comment by xaddict** [comment]
@lesda Please put a link to an example (codepen for example) and state your version. Wakirin is blazing fast with helping but you need to put as much detail and research into your bug as possible.

**Comment by lesda** [comment]
@xaddict the version is stated, 1.0.27 in a comment, will give an example link later today

**Comment by lesda** [comment]
Here is a jsfiddle: https://jsfiddle.net/v8fewpmc/

If you open the calendar, the 20-21-21 of March is booked, but if you hover over any day, for example 1s March, than the is-booked class is gone from 20-21-22 of March.

Furthermore if you set 'selectForward' to false, a second bug appears: opening a calendar works, but if you hover over any date is before 15th of March then the whole range selection freezes until you leave the whole calendar.

**Comment by wakirin** [comment]
Sorry, I don't understand what are you expected.
From your example:
`bookedDays: ['2020-03-20', '2020-03-21', '2020-03-22'],`

Are these three different booked days or you write the range as multiple days ?
From the previous discussion (#22)
> Guest 1 check-in: 2020-02-03 at the earliest 3 p.m.
> Guest 1 check-out: 2020-02-05 latest 11 a.m.
> Guest 2 check-in: 2020-02-05 at 3 p.m. at the earliest
> Guest 2 Check-Out: 2020-02-26 latest 11 a.m.

I think this is the correct behavior for hotels, single booked days can be selected as check-out date.
If you need to disable whole day then use `lockDays` instead of `bookedDays`.

**Comment by lesda** [comment]
That's just 3 dates I wanted to be booked, could have written a range as well, that's not the point.

My issue is that upon opening the calendar, the three booked date displayed as gray (due to the styling of is-booked class) - that is shown on the first screenshot I just uploaded, but if I start to hover on other days (second screenshot), the three booked day is displayed as regular days, without the is-booked class being applied on them. 

![Clipboard01](https://user-images.githubusercontent.com/11975010/71994722-8db20400-3239-11ea-9b7a-779bfb7cba67.jpg)
![Clipboard02](https://user-images.githubusercontent.com/11975010/71994723-8db20400-3239-11ea-9fea-e21fa5dc5f45.jpg)

**Comment by lesda** [comment]
I updated the fiddle with a few CSS rules to make the role of each date visually more distinguishable: https://jsfiddle.net/v8fewpmc/
So the issue is in short: all the red days disappear when the range selection via mouse hovering is active

**Comment by wakirin** [comment]
v1.0.28
https://jsfiddle.net/rtp5m8q4/

**Comment by lesda** [comment]
Thanks!
