### ISSUE TITLE
Picker not opening on button click when containing icon clicked

### ISSUE THREAD

**Issue by dwasyl** [wakirin/Litepicker#288]
Hi there,

I'm new to using Litepicker, but have a new picker setup as per the docs `element: document.getElementById('btn_calendar'),`, where `btn_calendar` is a simple button as `<button class="btn btn-sm" id="btn_calendar"><i class="bi bi-calendar-event"></i></button>`. However, the calendar will not popup when the user clicks the icon within the button, only when clicking the surrounding button.

Is there a way around this?

1. Create a `<button></button>` element with an icon as the button text.
2. Create a new `Litepicker` with an element target of a button element above.
3. Click on the icon within the button, observe the lack of calendar.

Thanks

**Comment by cedrickp32** [comment]
@dwasyl Hi, i had the exact same problem yesterday. My element is link with an svg icon. When i clicked on the padding around the icon, it was showing the calendar, but not when i clicked on the icon itself. 

I resolved this by adding a pointer-events:none on the svg like this:  `.calendar-link svg { pointer-events: none;}`

Hope this help !

**Comment by dwasyl** [comment]
@cedrickp32 that's perfect - did the trick right away. Thanks!
