### ISSUE TITLE
Refresh datepicker when input value is changed by user

### ISSUE THREAD

**Issue by Allmytc** [wakirin/Litepicker#29]
**Is your feature request related to a problem? Please describe.**
I'm using the singleMode and users would like (sometimes) to go to a different year (when a year is already in the input) by changing the value in the input (and not clicking on an arrow 12 or 24 times).
exemple
Value in input is by default 01/01/2020 and I'd like to go to 01/01/2018.

**Describe the solution you'd like**
An option when we create an instance to put the datepicker in 'AutoRefresh'

**Describe alternatives you've considered**
I wrote this little script to do it :
```HTML
<input type="text" id="litepicker" value="01/01/2020">
```
```javascript
var el = document.getElementById('litepicker')
piker = new Litepicker({
	element:  el,
	format: 'DD/MM/YYYY',
	lang: 'fr-FR'
});
el.addEventListener("keyup", function(e) {
	var changedDate = el.value;
	var pressedKey = e.which;
	if(pressedKey !== 37 && pressedKey !== 38 && pressedKey !== 39 && pressedKey !== 40 && isValidDate(changedDate)) {
		piker.setOptions({
			startDate: changedDate,
			endDate: changedDate
	});
	piker.setDate(changedDate);
	}
});

function isValidDate(dateString) {
	return /^(0[1-9]|[1-2][0-9]|3[0-1])\/(0[1-9]|1[0-2])\/\d{4}$/.test(dateString);
}
```

**Additional context**
I put the pressedKey test because it's easier to go somewhere in the input by using arrow of the keyboard and I don't want to refresh the datepicker on those user actions.

**Comment by wakirin** [comment]
Added in v1.2.1,
see option [`autoRefresh`](https://wakirin.github.io/Litepicker/#option-autoRefresh)
