### ISSUE TITLE
clone is not a function

### ISSUE THREAD

**Issue by sinankeskin** [wakirin/Litepicker#3]
**Describe the bug**
momentjs dependency is dropped therefore clone function cannot be used.

**To Reproduce**
1. Set a start date with string.
2. Immediately"this.options.startDate.clone is not a function" exception will be thrown.

**Expected behavior**
No exception.

**Comment by wakirin** [comment]
from docs:
> startDate
> Date Object or Unix Timestamp (with milliseconds) or String (must be equal to option format).

So if you try to set date with string, this string should be equal to option format (default format is YYYY-MM-DD).
`clone` is not part of momentjs, it is from extended class Date https://github.com/wakirin/Litepicker/blob/c7fc5768424d59125f3b30eb84d023ed046e9b96/src/datetime.ts#L134

Anyway I see other bug, `input` element doesn't update after `setDate`. https://jsfiddle.net/waki/1rqpjw4s/5/
I will fix it.

**Comment by sinankeskin** [comment]
Nope not set with setDate function. Set with startDate parameter.

[jsfiddle](https://jsfiddle.net/0x63r8so/)

You can see the error in console.

**Comment by wakirin** [comment]
Check please version 1.0.6

**Comment by sinankeskin** [comment]
This issue fixed. Thank you but If I don't give endDate parameter same exception throwing again.

[jsfiddle](https://jsfiddle.net/3h9a2c4x/1/)

**Comment by sinankeskin** [comment]
Is it by design? Also seems like if singleMode parameter is false user must choose end date now.

**Comment by wakirin** [comment]
Yes, from docs:
> startDate
> Preselect date. If option singleMode is disabled then endDate must be set too.

Of course, I will fix that error too. startDate will be ignored without endDate in disabled singleMode.

**Comment by sinankeskin** [comment]
Not that I didn't read the docs because I did. Actually it surprised me, because previous library has this option.

We are using this option for open end date ranges. User can select start date but no end date. For example: Logistics, Movement jobs, etc...

But your library, your rules. OK.
