### ISSUE TITLE
Issues migrating from (deprecated) Lightpick

### ISSUE THREAD

**Issue by chapeljuice** [wakirin/Litepicker#31]
Thanks for your work, love this calendar.

We're moving from Lightpick to Lightpicker and have some issues we didn't used to have.

- In Lightpick, we could set the booked days tooltip. Any way to do that here?
- We had multiple calendars on our page, and one of them was an inline calendar. For some reason after migrating, the inline calendar is not displaying. Is there any support for multiple calendars on a single page?

**Comment by wakirin** [comment]
> In Lightpick, we could set the booked days tooltip. Any way to do that here?
Litepicker doesn't have such options at the moment. I think I can add it in the future releases.

> We had multiple calendars on our page, and one of them was an inline calendar. For some reason after migrating, the inline calendar is not displaying. Is there any support for multiple calendars on a single page?
I don't see the problem: https://jsfiddle.net/ndxcy2t6/
Maybe some kind of problems with the styles ?
