### ISSUE TITLE
Year change Event

### ISSUE THREAD

**Issue by kl3sk** [wakirin/Litepicker#33]
**Is your feature request related to a problem? Please describe.**
With a recent version, we have dropdowns with year and month. But Year change still has no event

**Describe the solution you'd like**
Catch Year change event

**Comment by wakirin** [comment]
I forgot to update the docs, the event already exists:
https://jsfiddle.net/4f6p325o/

**Comment by wakirin** [comment]
Docs updated.

**Comment by kl3sk** [comment]
Ok good news, so don't forget to update it ;)
