### ISSUE TITLE
Custom date format

### ISSUE THREAD

**Issue by kl3sk** [wakirin/Litepicker#34]
**Is your feature request related to a problem? Please describe.**
It is impossible to add custom chars on `format` option.

**Describe the solution you'd like**
I'd like to be able to write down such format `YYYY-MM-DD\T00:00:00`

**Comment by wakirin** [comment]
Added in v1.5.0

https://wakirin.github.io/Litepicker/#option-format

**Comment by kl3sk** [comment]
@wakirin thanks it look like it work as expected, but :

I don't need to escape anything, is this an intended behavior ? (see: https://jsfiddle.net/klesk/fuedv7x4/)

Wait for the time picker module to be able to parse time too 😉

**Comment by wakirin** [comment]
See docs.

> You may escape formatting tokens using \\.
> 
> Eg.:
> 
> `format: 'YYYY-MM-DD\T00:00:00'`
>
> Result: **2020-01-01T00:00:00**

**Comment by kl3sk** [comment]
Yes I "may", but it looks not necessary.

It work the same. Am I wrong ?

**Comment by wakirin** [comment]
Yes, as long as this not a token it is not necessary.
I found wrong work with escaping, do not close this issue yet.

**Comment by kl3sk** [comment]
Then you have a typo in your doc 😉
