### ISSUE TITLE
[Feature Request] classes for Check-In only and Check-out only days

### ISSUE THREAD

**Issue by digitalredefned** [wakirin/Litepicker#36]
I'd love to see classes appended to dates that are check-in or check-out only.  Would make formatting them a breeze.  

Thanks!

**Comment by wakirin** [comment]
Well, I think you can use these classes`is-start-date` and `is-end-date`.

**Comment by digitalredefned** [comment]
@wakirin - I'm digging into this and though I'm not quite seeing how I can set these dates.  Is there a method I can use to set the dates with these css classes?
