### ISSUE TITLE
onSelect event handler conflicts with the onSelect event handler in React

### ISSUE THREAD

**Issue by kitsune7** [wakirin/Litepicker#38]
**Describe the bug**
When using the onSelect event handler in a React.js application, React.js's onSelect event is triggered but Litepicker's onSelect event isn't.

**To Reproduce**
1. Create or install a React.js application with Litepicker
2. Add an onSelect event handler
3. Call `console.log(date1, date2)` (where `date1` and `date2` are the parameters to the event handler function)
4. See a synthetic event from React.js and `undefined` instead of dates from Litepicker

**Expected behavior**
I expect Litepicker's onSelect event to either take precedence over React.js's onSelect event or for Litepicker to use an event handler name that doesn't conflict.

**jsfiddle.net / codepen.io / etc**
https://jsfiddle.net/p92a0wjx/

**Additional context**
React's onSelect: https://reactjs.org/docs/events.html#selection-events

**Comment by wakirin** [comment]
`onSelect` should be define in Litepicker https://jsfiddle.net/gd74rbs2/
