### ISSUE TITLE
Month names color in calendar popup

### ISSUE THREAD

**Issue by jsantari** [wakirin/Litepicker#4]
If you are using a dark theme where your text color is white the month names are not visible as the default background color is also white. Changing the background color helps but what is needed is a variable for the title color itself so it can be controlled.

**Comment by wakirin** [comment]
https://github.com/wakirin/Litepicker/blob/d9b3a4020140563a46db9911ce2141b3262066ac/src/scss/main.scss#L4

Added in v1.0.11
