### ISSUE TITLE
Copyright notice and licensing info header missing from the main.js file

### ISSUE THREAD

**Issue by pragmatechdev** [wakirin/Litepicker#41]
Please add copyright notice and licensing info at the begining of the main.js file.
Also, make sure the comment is not removed from the minified version.
```
/*
 * Litepiker V1.0.31 (https://github.com/wakirin/Litepicker)
 * Copyright 2019-2020 Rinat G.
 * Licensed under MIT (https://github.com/wakirin/Litepicker/blob/master/LICENCE.md)
*/
```
Your library cannot be legally used in other projects unless copyright and licensing info are included in the source code. Either directly by you like above or manually by each developer who is using it.
Thank you.

**Comment by wakirin** [comment]
Thanks for information, copyright added.
