### ISSUE TITLE
Uncaught TypeError on NPM installed package

### ISSUE THREAD

**Issue by dough14** [wakirin/Litepicker#42]
First of all, thanks for the development of this incredible datepicker!

When I try to import the Litepicker to a Angular 1.x custom component I've got the following error bellow:
`Uncaught TypeError: Method Date.prototype.setDate called on incompatible receiver [object Object]`

The strangest part is that if I try to use the Litepicker via CDN, instead of via NPM, the error disapear and all works properly.

I've tried to track the problem inside the NPM installed package but uncessfully.

**Comment by wakirin** [comment]
I assume that this error related to #53 and should be fixed in v1.2.0
