### ISSUE TITLE
Add a reset button directly into the picker

### ISSUE THREAD

**Issue by EmilienLeroy** [wakirin/Litepicker#46]
**Is your feature request related to a problem? Please describe.**
To clear a selection i need to add an external button.

**Describe the solution you'd like**
Add a simple button to clear the current selection and into the options add a new field `displayClearBtn` or something like that.

**Additional context**
Something like that can be really helpfull i think. (Here i have added my own button)
![clearBtn](https://user-images.githubusercontent.com/31723722/76963745-d533cb00-6921-11ea-81d2-68714f4a6bd2.gif)

**Comment by wakirin** [comment]
If you already done this, you can create PR.
Thanks.
