### ISSUE TITLE
week numbers are off

### ISSUE THREAD

**Issue by sfusato** [wakirin/Litepicker#5]
week numbers are not properly displayed. See screenshot below from demo site:
![showWeekNumbers-bug](https://user-images.githubusercontent.com/19363153/69886388-04c2b700-12e2-11ea-814e-6db646485f6a.png)

**Comment by wakirin** [comment]
I guess this happened when I switched from grid to flexbox.
Check please v1.0.12, this version contains a fix for this problem.

**Comment by sfusato** [comment]
It's fixed in the new version. Thank you!
