### ISSUE TITLE
Shadow DOM Support

### ISSUE THREAD

**Issue by jevenson** [wakirin/Litepicker#50]
**Is your feature request related to a problem? Please describe.**
Currently, this component does not support Shadow DOM. If my code base is written to take advantage of Shadow DOM, and I attach the litepicker to an element inside of a shadowed custom element, the litepicker will not open when clicking on the bound element. This is because when clicking on an element in the Shadow DOM, the root custom element is emitted as the clicked element, and not the actual child element clicked.

When the litepicker is initialized, it sets up a click handler on the document. Using that handler, if it detects that the element or elementEnd was clicked, it will open. This same handler is used to determine if the picker should close.

**Describe the solution you'd like**
In addition to the document click event handler, this problem could be fixed by adding a click handler directly to the element passed to the litepicker. By doing this, the litepicker will know exactly when the element was clicked, instead of its parent custom component.

Here is the code I've implemented, it appears to be working. The onClick function will need some changes made in order to detect if the element or elementEnd was clicked and being handled in the document click handler, so the event is not being handled twice.

```Typescript
  litepicker.ts

  private onInit() {
    // Existing document click handler
    document.addEventListener('click', e => this.onClick(e), true);

    // New event handler for the element
    this.options.element.addEventListener('click', e => this.onClick(e), true);

    // New event handler for the elementEnd, if it exists
    if (this.options.elementEnd) {
      this.options.elementEnd.addEventListener('click', e => this.onClick(e), true);
    }

    ...
   }
```

**Additional context**
Some example code

```html
<my-custom-component> <!-- This is a shadowed component -->
    <input class="date" />
</my-custom-component>
```

```Typescript
const datepicker = new Litepicker({
   element: document.querySelector('my-custom-component').shadowRoot.querySelector('.date')
});
```
When clicking on `<input class="date" />`, the `<my-custom-component>` element is emitted as the clicked element from the document click handler, so the datepicker does not open.

**Comment by wakirin** [comment]
I see that this can work without PR.
Let me know if I missed something.

https://jsfiddle.net/wn6dcbv3/
