### ISSUE TITLE
Support setting startDate and endDate individually

### ISSUE THREAD

**Issue by jevenson** [wakirin/Litepicker#52]
**Is your feature request related to a problem? Please describe.**
I'm using the litepicker with an `element` and `elementEnd`, and not in single mode. `element` and `elementEnd` are both inputs. Currently, when I manually type a date into the start date input, the value is cleared out, because the end date was not also provided. Same thing happens when you provide an end date without the start date.

I'm wondering if you'd be open to a pull request to remove the need for both dates to be provided at the same time, and also allowing the end date to be set independently. I think I have it mostly working in a fork of this repository, but more testing will be required to make sure these changes don't break anything else.

**Describe the solution you'd like**
I made several changes to `litepicker.ts` and `methods.ts` to treat start and end dates independently. This involved updating the constructor, `parseInput`, `updateInput` and `onInput` functions.

**Describe alternatives you've considered**
N/A

**Additional context**
I'll have a branch pushed up soon for you to take a look at if you're interested

**Comment by wakirin** [comment]
Can be these changes be optionally ? To prevent breaking current behavior.

**Comment by wakirin** [comment]
However, when you use both elements (`element`, `elementEnd`) individually looks like more logical.
PR is welcome.
Thanks.

**Comment by scott-fisher-iii** [comment]
I haven't tried with this date picker yet, but others have allowed you to have two date pickers (one for start date; one for end date) and then you just set the min/max date of each picker to the value of the other field.

**Comment by wakirin** [comment]
Use [easepick](https://easepick.com/) with [range-plugin](https://easepick.com/packages/range-plugin)
Option: `strict: false`

https://jsfiddle.net/waki/gh378m10/
