### ISSUE TITLE
Ability to show predefined date ranges for selection

### ISSUE THREAD

**Issue by MediumBrownToast** [wakirin/Litepicker#57]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to pre-define a set of date ranges that could be used by the user as a type of shortcut. For example, next to the calendar display could be a list of the 'shortcuts'. e.g. "Today", "Last Week", "Last Month", "Last Year". When "Last Week" is selected, for example, the date range is updated with Day.now() and Day.now() minus 7 days. 

**Describe alternatives you've considered**
I can create separate buttons that use the Litepicker.setDateRange() method to achieve the same result, but it would be nice to have the options integrated into the same interface. (I am far from an expert so apologies if this is already possible).

**Additional context**
NA

**Comment by wakirin** [comment]
Added in v1.3.0
Made as a separate module: https://github.com/wakirin/litepicker-module-ranges
See docs: https://wakirin.github.io/Litepicker/#option-moduleRanges

https://jsfiddle.net/6x58y92e/1/
