### ISSUE TITLE
[Feature Request] Option for Custom Styles

### ISSUE THREAD

**Issue by tmswr** [wakirin/Litepicker#6]
I'd like to see the option for Custom CSS which could add readable class names and remove everything but fundamental CSS (grid, etc.). Similar to [Lightpick](https://wakirin.github.io/Lightpick/). The ability to customize to the UI without having to use `!important` for basic UI changes (like fonts) would help Litepicker match the existing style of a site.

**Comment by wakirin** [comment]
I'll think about it.

**Comment by harrync** [comment]
Seconded, this was a great feature of Litepik

**Comment by glo-www** [comment]
Same here, I would like to use my own CSS. Currently I don't know how to do that. Readable classe names with no inline css would be great.

**Comment by tmswr** [comment]
> Same here, I would like to use my own CSS. Currently I don't know how to do that. Readable classe names with no inline css would be great.

You can style it with a ton of `!important` use, however there's no easy way of telling that `._2CguzoMvitxdFkSfaWOxfO` = disabled days, or that `._1DjTnqKn6cOy17CdpYA1OB` and `._38t4MIvz_F8jLJqXffcjyB` are the previous/next buttons.

**Comment by metalandcoffee** [comment]
I was super excited for your new datepicker! But the loss of human readable class names is a big deal. Hope you decide to make things more flexible :)

**Comment by wakirin** [comment]
Changed in v1.0.18
Class names are readable.

**Comment by metalandcoffee** [comment]
WOOHOO!!! Thanks, @wakirin P.S. I love The Witcher!

**Comment by tmswr** [comment]
> WOOHOO!!! Thanks, @wakirin P.S. I love The Witcher!

Not all heroes wear capes... this one just happens to! Thank you @wakirin!
