### ISSUE TITLE
Add SCSS file to npm package

### ISSUE THREAD

**Issue by sinankeskin** [wakirin/Litepicker#65]
**Is your feature request related to a problem? Please describe.**
No. It's for anyone who wants to use SASS in their project.

**Describe the solution you'd like**
Simply add scss file to npm package.

**Describe alternatives you've considered**
None.

**Additional context**
Also for anyone who use LESS you can convert the file to less.

Thank you.

**Comment by wakirin** [comment]
Styles are already included in the `main.js` file.
Therefore, I believe that there is no reason to publish the`scss` file in the npm package.

**Comment by sinankeskin** [comment]
Hımm different perspective. Thanks.
