### ISSUE TITLE
When autoApply is false, the range text in the picker blends in with other text on the page.

### ISSUE THREAD

**Issue by scott-fisher-iii** [wakirin/Litepicker#68]
**Describe the bug**
When autoApply is set to false and the picker is bound to two textboxes, the selected date range in the picker shows next to the Apply and Cancel buttons. This text is very hard to read (or even notice).

**To Reproduce**
1. Have a datepicker bound to two textbox elements with autoApply set to false.
2. Below the textbox elements have a page of text
3. Select a date range in the picker.
4. The text display of the range at the bottom left of the picker becomes visible, but doesn't stand out.

**Expected behavior**
I think we just need some tweaks to the styling to make this text more visible.
Perhaps add a border or a different background color to the range text (or entire button row?).

**Comment by wakirin** [comment]
You can control the style of this text via class `preview-date-range`.

https://jsfiddle.net/1fm4ud5n/1/

**Comment by scott-fisher-iii** [comment]
Good to know. Thank you!
