### ISSUE TITLE
Unable to change start date with two textboxes and autoApply set to false

### ISSUE THREAD

**Issue by scott-fisher-iii** [wakirin/Litepicker#69]
**Describe the bug**
When an existing range is selected and autoApply is set to false and allowRepick set to true, you cannot reselect the start date.

**To Reproduce**
1. Bind a date picker to two textbox elements with autoApply set to false.
2. Select a date range and click Apply.
3. Relaunch the picker to repick only the start date and click Apply
4. The two textboxes are then populated with the end date.
5. Repeat the test, but set autoApply to true and the problem disappears.

**Expected behavior**
Allow both the start and end dates to be changed when allowRepick is set to set regardless of the autoApply setting.

**Comment by wakirin** [comment]
> 3. Relaunch the picker to repick only the start date and click Apply

`Apply` is inactive without end date.
https://jsfiddle.net/1fm4ud5n/

Please give an example on jsfiddle.

**Comment by scott-fisher-iii** [comment]
Your jsfiddle was missing the allowRepick: true.
When I add that I see the problem on demand.

https://jsfiddle.net/d1gv2kp5/

**Comment by wakirin** [comment]
fixed in v1.3.0
https://jsfiddle.net/sgtrfc7h/

**Comment by scott-fisher-iii** [comment]
I can confirm this is resolved. Thanks for the quick turnaround!
