### ISSUE TITLE
Show previous months instead of next

### ISSUE THREAD

**Issue by rozbyn** [wakirin/Litepicker#7]
Hello. I have a question about "Litepicker".
I use "numberOfMonths" = 2 and "numberOfColumns" = 2. Suppose a user selects the date "10/10/2019" and after that opens "Litepicker" again. Now the first column will display 10th months, and the second 11 months. 
![Screenshot_40](https://user-images.githubusercontent.com/34918480/70141690-aa8e7100-16a8-11ea-8b22-2f53cebe52f2.png)

How can I make the previous month (09) appear in the first column and the currently selected one (10) in the second?
![Screenshot_41](https://user-images.githubusercontent.com/34918480/70141716-bc701400-16a8-11ea-8d0b-8c6cc9222840.png)

Is there such an option now? If not, that would be helpful.
In my task, the user needs to select a date (or a range of dates) in the past, not in the future, so showing him the next month does not make much sense.

**Comment by wakirin** [comment]
Hello,
there are no options for this case, but you can use the `onShow` event.
Example: https://jsfiddle.net/waki/pr1gda8w/5/

**Comment by rozbyn** [comment]
Wow! Thank you very much!

**Comment by atuldubey007** [comment]
Hi. The onShow method doesn't work for inline mode. Please suggest something for that.

**Comment by wakirin** [comment]
@atuldubey007 `inlineMode` always displays a calendar, why do you need the `onShow` event ?

**Comment by atuldubey007** [comment]
I am not able to implement the solution that you provided above in https://jsfiddle.net/waki/pr1gda8w/5/ for inline mode.

**Comment by wakirin** [comment]
@atuldubey007 maybe it will help: https://jsfiddle.net/37e8jqac/

**Comment by atuldubey007** [comment]
Thanks for the update. However, I was hoping for it to work on init because I want the user to select only previous dates and not future dates. So, when I create a 3-column 3-month layout, it shows the current date on left, rather than right.
