### ISSUE TITLE
Unable to select range using month/year dropdowns

### ISSUE THREAD

**Issue by scott-fisher-iii** [wakirin/Litepicker#70]
**Describe the bug**
Using the months and years dropdowns resets any selected date. If I am trying to select a range, I must use the arrows after picking my first date.

**Setup**
```
var picker = new Litepicker({
   element: <input ... />,
   elementEnd: <input ... />,
   dropdowns: {
      minYear: new Date().getFullYear() - 150,
      maxYear: new Date().getFullYear() + 100,
      months: true,
      years: true
   },
   minDate: new Date(1753, 01, 01), // Minimum value of SQL DATETIME type
   allowRepick: true,
   autoApply: true,
   singleMode: false
});
```

**To Reproduce**
1. Set up a datepicker for two input elements.
2. Open the datepicker.
3. Select a date.
4. Change the month/year dropdown.
5. The datepicker forgets the first date and your next date is treated as your first.

**Expected behavior**
Changing the month/year via the dropdowns should not lose a previously selected date.

**Comment by wakirin** [comment]
Cannot reproduce this problem.

https://jsfiddle.net/1fm4ud5n/2/

**Comment by wakirin** [comment]
I think this problem is related to #69
