### ISSUE TITLE
Bookable days instead of booked days

### ISSUE THREAD

**Issue by gvdlangenberg** [wakirin/Litepicker#72]
Hey there! First of all, thanks for this nice plugin. It's difficult to find a decent datepicker in vanilla js these days.

I was wondering if the next thing is possible. Currently I'm having an array with bookable days, instead of booked days. At this point I need to make a function to get the difference between these bookable days and the range of possible dates:

```
import Moment from 'moment';
import difference from 'lodash/difference';

export function getBookedDays(bookableDays) {
    const today = Moment();
    const endOfNextYear = Moment().add(1, 'year').endOf('year');

    const dates = [];
    let day = today;

    while (day <= endOfNextYear) {
        dates.push(day.format(DEFAULT_SYSTEM_DATE_FORMAT));
        day = day.clone().add(1, 'day');
    }

    return difference(dates, bookableDays);
}
```
This array can get quite large and especially Safari seems to get some serious performance issues when the bookedDays array gets too large.

If there would be a property like `bookableDays` it would help me a lot! Or maybe something like a disableDayFn that gets triggered for every day every time you switch months. Looking forward to your response. 

Thanks!

**Comment by wakirin** [comment]
> Moment().add(1, 'year').endOf('year');

May I ask, why you use such a large range instead of the visible range on the calendar ?

**Comment by gvdlangenberg** [comment]
Yes this resolved the performance issue, nevertheless, this still needed some custom functionality to get this to work. Would be nice if this would work out of the box 😄

**Comment by wakirin** [comment]
Well, I think the library should not filter dates, you yourself must control what dates you send via `setBookedDays`.

**Comment by wakirin** [comment]
v1.3.2
Added new event `onRenderDay`.
Other things are not planned to be implemented.
Example with `onRenderDay`: https://jsfiddle.net/acbzw17h/2/
Note: the «Heavy» function in `onRenderDay` may affect performance.

**Comment by strarsis** [comment]
@wakirin: This is so awesome! ❤️ Thanks!

**Comment by strarsis** [comment]
@wakirin: Related: https://github.com/wakirin/Litepicker/issues/116
When the user selects a start date, the day render rules may change, hence an event should be available for changing the state of day render rules (and allow a refresh).
