### ISSUE TITLE
`setOptions` made a wrong check against the type of `this.options.startDate`

### ISSUE THREAD

**Issue by nightire** [wakirin/Litepicker#75]
In the `setOptions` method, there's a line of checking if `this.options.startDate` is an instance of `Date`; however, it's an instance of the custom `DateTime` class. Thus this condition will never be `true`:

https://github.com/wakirin/Litepicker/blob/f29fdcb33916f1a4b60a44787eb556b7089aae3f/src/methods.ts#L314-L317

This bug prevents users from updating the `startDate` option manually.

**Comment by wakirin** [comment]
Nice catch! 
Fixed in v1.3.3
