### ISSUE TITLE
Dropdowns don't show correct year when out of range

### ISSUE THREAD

**Issue by oodavid** [wakirin/Litepicker#77]
Using these settings:

```
dropdowns: {
  minYear: 2019,
  maxYear: 2021,
  months: true,
  years: true,
},
```

The dropdown is correct when the date is after maxYear:

<img width="302" alt="Screenshot 2020-05-06 at 21 36 23" src="https://user-images.githubusercontent.com/46879/81225779-b4165f00-8fe1-11ea-9a49-4ebac77079f3.png">

But incorrect when the date is before minYear:

<img width="302" alt="Screenshot 2020-05-06 at 21 37 52" src="https://user-images.githubusercontent.com/46879/81225867-dad49580-8fe1-11ea-821f-47c7a6628630.png">

There's two ways of getting in this state:

1. Use the prev button to move back
2. Use a startDate before the minYear

**Comment by wakirin** [comment]
Fixed in v1.3.3
https://jsfiddle.net/a76L3vo8/
