### ISSUE TITLE
clearSelection doesn't reset the view

### ISSUE THREAD

**Issue by oodavid** [wakirin/Litepicker#78]
If I run `.clearSelection()`, then re-activate the picker, the modal still remembers the old view (ie, the highlighted month).

I tried running `.setDate(new Date())` prior to clearSelection, however that triggered the `onSelect` event which had unexpected behaviour.

clearSelection should reset the view to today.

**Comment by wakirin** [comment]
Give an example where you have this problem, please.
I checked here: https://jsfiddle.net/8r3nLvo2/

**Comment by wakirin** [comment]
Well, I thought about this problem.
`clearSelection` should only clear the date range (as the method is named).
You can go to a specific date after clearing with the `gotoDate` method, it is doesn't trigger `onSelect`.
Example: https://jsfiddle.net/04rvwn75/

**Comment by scott-fisher-iii** [comment]
I think usability wise if you have cleared a selection, I would expect the next launch of the datepicker to be at today's date. That seems to be consistent with other pickers.

**Comment by wakirin** [comment]
Well, I don't plan to change the behavior of `clearSelection`.
You can still use `gotoDate` after `clearSelection`.

**Comment by scott-fisher-iii** [comment]
That makes sense. Was just an observation from the user perspective.
It is probably a good idea for anyone using clearSelection to also use gotoDate after.
