### ISSUE TITLE
Crossing over some days causes number of days to be a decimal

### ISSUE THREAD

**Issue by d2roth** [wakirin/Litepicker#8]
**Describe the bug**
When showing the number of days it shows a decimal number of days over March 8th-9th 2019.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://wakirin.github.io/Litepicker/
2. Click on the date picker on the right.
3. Navigate until you see March 2020
4. Select March 8th as the start date and mouse over March 9th
5. See error

**Expected behaviour**
The days should show 2 days not 1.95 days

**Screenshot**
https://prnt.sc/q6n7w8

**Comment by wakirin** [comment]
Hi,
check v1.0.16. 
`Math.round` added to the `diff` function if the unit is days.
https://github.com/wakirin/Litepicker/blob/c5c5a92a7f251c8d52bcba2a7fc1da0f138c5c54/src/datetime.ts#L308
