### ISSUE TITLE
Two separate date inputs for range

### ISSUE THREAD

**Issue by strarsis** [wakirin/Litepicker#80]
**Is your feature request related to a problem? Please describe.**
It would make sense to use Litepicker on two separate date inputs for start/end date range.

**Describe the solution you'd like**
Litepicker supports two date input elements.

**Describe alternatives you've considered**
Offer two date inputs for a date range and hide them when Litepicker is used.

**Comment by wakirin** [comment]
Have you see [`elementEnd`](https://wakirin.github.io/Litepicker/#option-elementEnd) in the docs ?

**Comment by strarsis** [comment]
@wakirin: Excellent, awesome! Now I am torn between flatpickr and Litepicker (this one). What would you recommend?

**Comment by s1awek** [comment]
> Have you seen [`elementEnd`](https://wakirin.github.io/Litepicker/#option-elementEnd) in the docs ?

Sorry, but I can't get it to work the way it works here: : https://wakirin.github.io/Lightpick/ (Option: secondField)
I tried a couple of ways but nothing seams to work.
