### ISSUE TITLE
Support data-* attributes as configuration

### ISSUE THREAD

**Issue by marvinschroeder** [wakirin/Litepicker#84]
Would be great to see usage of data-* attributes on the input element as configuration.
So for example this:

`<input id="litepicker" data-start-date="2020-05-15" data-end-date="2020-05-20" data-lang="de-DE">`

`var picker = new Litepicker({ element: document.getElementById('litepicker') });`

This is the same as this:

`<input id="litepicker">`

`var picker = new Litepicker({
element: document.getElementById('litepicker'),
startDate: "2020-05-15",
endDate: "2020-05-20",
lang: "de-DE"
});`

**Comment by wakirin** [comment]
Added in v1.4.4
Does not support options like `object` (e.g. dropdowns, buttonText, tooltipText)  or `function` (all events).
