### ISSUE TITLE
Release compiled JS

### ISSUE THREAD

**Issue by apinsard** [wakirin/Litepicker#85]
Hello, I just discovered this wonderful date range picker. I've been looking for something like that, working as well on desktop than mobile, for years. It ships with everything I need and works very well, that's awesome! Congratulations!

Afaic, I'm not a big fan of npm installs. I hate having to pull loads of useless stuff on my environment just to install some javascript libs. I have my own system to retrieve my JS dependencies and upgrade them from github and other sources.

It would be very appreciated to have the compiled `.js` and/or `.min.js`, either available directly in the repository, or included in [github releases assets](https://developer.github.com/v3/repos/releases/#upload-a-release-asset).

For now I'm using https://cdn.jsdelivr.net/npm/litepicker/dist/js/main.js but it doesn't allow me to choose the version number.

Thank you very much for the awesome work!

**Comment by scott-fisher-iii** [comment]
You can specify a version number.

Here is v1.3.4:
https://cdn.jsdelivr.net/npm/litepicker@1.3.4/dist/js/main.js
