### ISSUE TITLE
Missing buttons in `buttonText` should keep default value, not "undefined"

### ISSUE THREAD

**Issue by apinsard** [wakirin/Litepicker#87]
**Describe the bug**
If I want to change the text of only one button, I have to define the text for all buttons in `buttonText`, otherwise they are set to "undefined". This is especially inconvenient for previousMonth, nextMonth and reset, which I'd have to find the original SVG to copy/paste.

![Screenshot_2020-05-15 Locations courte durée Rennes – Tourisme ou Affaires – Cocoonr(1)](https://user-images.githubusercontent.com/1536035/82079408-1c9cc480-96e3-11ea-8058-dcf267ffd7fc.png)

**To Reproduce**
1. Set option `{buttonText: {apply: "OK", cancel: "Annuler"}}`
2. Open the widget.

**Expected behavior**
When an option is undefined, it should keep the default value.

**Comment by wakirin** [comment]
Fixed in 1.4.4
