### ISSUE TITLE
Language setting doesn't work for "tooltip"

### ISSUE THREAD

**Issue by RonaldKools** [wakirin/Litepicker#91]
**Describe the bug**
When you set the language to something not English, like nl-NL or de-DE, the tooltip still says "day" or "days" instead of a translated name. 

**To Reproduce**
1. setup the plugin using this setup:
`var picker = new Litepicker({
singleMode: false,
element: document.getElementById('yourElement'),
format: "DD-MM-YYYY",
lang: "de-DE"
});
`
2. select a date - it will say "1 day" even though I set the language to German
3. select an ending date - it will now say "days" 
 
**Expected behavior**
Would be nice to see all in the same language.

**jsfiddle.net / codepen.io / etc**
https://jsfiddle.net/0se2ok6v/

**Comment by RonaldKools** [comment]
Never mind. Was fixed in 1.4.6 ;-)

**Comment by ninetyninew** [comment]
Hey @RonaldKools we have the same issue, we can see it working on https://wakirin.github.io/Litepicker/ but it isn't working on our website (it translate everything else just not the tooltips) - did you find out why?

**Comment by RonaldKools** [comment]
If I remember correctly the version on https://wakirin.github.io/Litepicker/ itself was newer/different from the one you get offered to download, so I ended up using that one instead.

**Comment by danielbehrendt** [comment]
Same problem here, tooltips won't get translated. It would be nice to have an option to set the values for "day" and "days" tooltips.
