### ISSUE TITLE
Change years dropdown sort direction

### ISSUE THREAD

**Issue by scott-fisher-iii** [wakirin/Litepicker#93]
**Is your feature request related to a problem? Please describe.**
It would be nice to flip the dropdown lists to display in the opposite order.
We are using this datepicker for a reports utility (among other things) and often are picking a year in the past rather than the future.
Think of entering someone's birth date, that would be a past year rather than a future year.

**Describe the solution you'd like**
Provide an additional option to the dropdowns object to determine the sort direction.

**Comment by scott-fisher-iii** [comment]
I would imagine it would just be having a boolean condition wrapping this section in calendar.ts:
<pre>      for (let x = maxYear; x >= minYear; x -= 1) {
        const option = document.createElement('option');
        const optionYear = new DateTime(new Date(x, 0, 1, 0, 0, 0));
        option.value = x;
        option.text = x;
        option.disabled = (this.options.minDate
          && optionYear.isBefore(new DateTime(this.options.minDate), 'year'))
          || (this.options.maxDate
            && optionYear.isAfter(new DateTime(this.options.maxDate), 'year'));
        option.selected = date.getFullYear() === x;

        selectYears.appendChild(option);
      }</pre>

If ascending year sort, then keep it as is. If descending year sort, then flip the for statement to something like:
<pre>for (let x = minYear; x <= maxYear; x += 1)</pre>

The new setting could be something like:
<pre>    var picker = new Litepicker({
        element: elDate,
        dropdowns: {
            minYear: 1900,
            maxYear: 2050,
            months: true,
            years: true,
            sortAscending: false // NEW
        }
    });</pre>

I don't think it needs to apply to the months dropdown, just the years dropdown.

**Comment by wakirin** [comment]
Added in v1.4.7
Use `asc` instead of `true` for `years`.

Eg.:
```
        dropdowns: {
            minYear: 1900,
            maxYear: 2050,
            months: true,
            years: 'asc',
        }
```

**Comment by scott-fisher-iii** [comment]
Tested and confirmed in JSFiddle with v1.4.7.
