### ISSUE TITLE
Change dash/delimiter between the dates (date range)

### ISSUE THREAD

**Issue by strarsis** [wakirin/Litepicker#94]
@wakirin:
**Is your feature request related to a problem? Please describe.**
Some services, e.g. facet WP plugin, require a specific format for the date range.
Litepicker currently delimits the start and end date of a date range by using a dash, surrounded by spaces.
I want to have the date range in a format that only uses the dash as delimiter, without any spaces.

**Describe the solution you'd like**
A output format option? Sure, the user still wants to see the nicely formatted and localized date string in the input field. But when the form is submitted and that field is send, the date range format should be configurable.

**Describe alternatives you've considered**
Using a hidden field, set in Litepicker `onSelect`. But this is very hacky and also requires parsing the datetime first.

**Additional context**

**Comment by wakirin** [comment]
Added in v1.5.0

https://wakirin.github.io/Litepicker/#option-delimiter

**Comment by strarsis** [comment]
@wakirin: Awesome!

**Comment by strarsis** [comment]
@wakirin: A new release to npm would be great!
