### ISSUE TITLE
Trigger onSelect (or other event) when user types a different date

### ISSUE THREAD

**Issue by ambischof** [wakirin/Litepicker#98]
**Is your feature request related to a problem? Please describe.**
When the user types in a date or changes a number via typing, the picker does pick up on these changes but doesn't seem to emit any events that are easy for the code to pick up, making it hard to keep in sync.

The `change` event is only just so helpful (see alternative section below), I'd much rather just listen for an event like I do when the user uses the picker.

**Describe the solution you'd like**
When the user changes the date via typing, an event should trigger so that code can update.

**Describe alternatives you've considered**
My code currently has a `change` listener, however, this is less than ideal because when the change is triggered, the picker has not yet updated. A next tick is not typically enough, so I am currently setting a timeout of 10ms before.

**Comment by scott-fisher-iii** [comment]
I too would want this. I also wired up a change event listener to handle this case.
We ended up making the textbox readonly in many places to force the user to enter dates via the datepicker.

**Comment by wakirin** [comment]
fixed in v1.4.7

**Comment by ambischof** [comment]
@wakirin Thank you!
