### ISSUE TITLE
Reference Error: window is not defined

### ISSUE THREAD

**Issue by lanceliamll** [wakirin/Litepicker#99]
While building and deploying an app. window is not defined error appear

1. Once you have the app working try to deploy your app.

it says
Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'

This should be able to work.

Need your help TIA

**Comment by wakirin** [comment]
Could you give a little more information about your development environment ?

**Comment by struckm** [comment]
I'm running into the same issue. It's related to Server Side Rendering(SSR). For me, I'm trying to build a Gatsby project and running into this issue. You would run into the same issue with NextJS as well, since they are both doing SSR.

**Comment by wakirin** [comment]
https://wakirin.github.io/Litepicker/docs/examples#how-to-add-litepicker-to-nuxtjs-
